export type CollocationItem = {
  id: string;
  phrase: string;
  translation: string;
  definition: string;
  example: string;
  examTip: string;
  category: "phrasal-verbs" | "collocations" | "idioms" | "formal-linkers";
};

export const b2Collocations: CollocationItem[] = [
  {
    id: "col-01",
    phrase: "come up with",
    translation: "farsi venire in mente / ideare",
    definition: "to think of or produce an idea, plan, or solution",
    example: "The marketing team came up with a brilliant strategy for the new campaign.",
    examTip: "Spessissimo richiesto nel Use of English Part 4 in combinazione con 'idea' o 'solution'.",
    category: "phrasal-verbs",
  },
  {
    id: "col-02",
    phrase: "take into account",
    translation: "tenere in considerazione",
    definition: "to consider particular facts or circumstances when making a decision",
    example: "You must take into account the additional transport costs before booking.",
    examTip: "Equivale a 'take into consideration' e si usa regolarmente nelle trasformazioni di frase.",
    category: "collocations",
  },
  {
    id: "col-03",
    phrase: "put up with",
    translation: "tollerare / sopportare",
    definition: "to accept or tolerate an unpleasant situation or person without complaining",
    example: "I cannot put up with this constant noise from the street any longer.",
    examTip: "Sinonimo B2 di 'tolerate' o 'stand'. Nota: richiede sempre il gerundio (-ing) se seguito da un verbo.",
    category: "phrasal-verbs",
  },
  {
    id: "col-04",
    phrase: "make ends meet",
    translation: "sbarcare il lunario / far quadrare i conti",
    definition: "to have just enough money to pay for the things you need",
    example: "With rising inflation, many university students struggle to make ends meet.",
    examTip: "Espressione idiomatica tipica dei testi di reading socio-economici B2.",
    category: "idioms",
  },
  {
    id: "col-05",
    phrase: "look forward to",
    translation: "non vedere l'ora di",
    definition: "to feel pleased and excited about something that is going to happen",
    example: "We are really looking forward to visiting the exhibition next weekend.",
    examTip: "TRAPPOLA D'ESAME: 'to' è una preposizione, quindi vuole sempre la forma in -ING (es. 'look forward to meeting you').",
    category: "phrasal-verbs",
  },
  {
    id: "col-06",
    phrase: "take for granted",
    translation: "dare per scontato",
    definition: "to never think about something because you believe it will always be available",
    example: "Clean running water is something many people take for granted.",
    examTip: "Frequente nel Use of English Part 4: 'take it for granted that...'.",
    category: "collocations",
  },
  {
    id: "col-07",
    phrase: "carry out",
    translation: "svolgere / eseguire",
    definition: "to perform or complete a task, experiment, or investigation",
    example: "Researchers are carrying out a series of tests to verify the initial hypothesis.",
    examTip: "Collocazione formale con 'research', 'survey', 'investigation' e 'experiment'.",
    category: "phrasal-verbs",
  },
  {
    id: "col-08",
    phrase: "on the verge of",
    translation: "sul punto di / sull'orlo di",
    definition: "very close to an event or state happening",
    example: "Scientists believe they are on the verge of a major medical breakthrough.",
    examTip: "Spesso seguito da un sostantivo o verbo in -ing. Sinonimo di 'on the brink of / about to'.",
    category: "collocations",
  },
  {
    id: "col-09",
    phrase: "call off",
    translation: "annullare / cancellare",
    definition: "to decide that a planned event or meeting will not happen",
    example: "The outdoor concert had to be called off due to extreme thunderstorms.",
    examTip: "Sinonimo informale di 'cancel'. Frequente nelle domande di ascolto (Listening Part 1).",
    category: "phrasal-verbs",
  },
  {
    id: "col-10",
    phrase: "bear in mind",
    translation: "tenere a mente / ricordare",
    definition: "to remember a piece of information when making a decision or judgement",
    example: "Bear in mind that the library closes earlier on bank holidays.",
    examTip: "Utilizzato come sinonimo di 'keep in mind' nei test di riscrittura frase.",
    category: "collocations",
  },
  {
    id: "col-11",
    phrase: "make up for",
    translation: "compensare / rimediare a",
    definition: "to compensate for something bad or missing with something good",
    example: "He bought her some flowers to make up for arriving late to dinner.",
    examTip: "Sinonimo di 'compensate for'. Essenziale nelle trasformazioni con parola chiave.",
    category: "phrasal-verbs",
  },
  {
    id: "col-12",
    phrase: "play a vital role in",
    translation: "svolgere un ruolo cruciale in",
    definition: "to be an important factor in achieving or causing something",
    example: "Diet and regular exercise play a vital role in maintaining cardiovascular health.",
    examTip: "Espressione accademica perfetta per ottenere punteggio alto nel Writing (Essay B2).",
    category: "collocations",
  },
  {
    id: "col-13",
    phrase: "turn down",
    translation: "rifiutare / respingere (un'offerta)",
    definition: "to refuse or reject an offer, invitation, or application",
    example: "She turned down the job offer because the salary was not competitive.",
    examTip: "Può significare anche 'abbassare il volume' (es. turn down the music), ma negli esami B2 indica 'reject'.",
    category: "phrasal-verbs",
  },
  {
    id: "col-14",
    phrase: "catch up with",
    translation: "mettersi in pari / raggiungere il livello",
    definition: "to reach the same quality, standard, or position as someone else",
    example: "I missed two lectures, so I need to study all weekend to catch up with the class.",
    examTip: "Spesso testato in contrasto con 'keep up with' (mantenere il passo).",
    category: "phrasal-verbs",
  },
  {
    id: "col-15",
    phrase: "with flying colours",
    translation: "a pieni voti / con grande successo",
    definition: "with very high grades or outstanding success",
    example: "After months of rigorous preparation, Marco passed his B2 exam with flying colours.",
    examTip: "Modo di dire immancabile nei contesti accademici e d'esame.",
    category: "idioms",
  },
  {
    id: "col-16",
    phrase: "get the hang of",
    translation: "prenderci la mano / imparare a padroneggiare",
    definition: "to learn how to do or use something through practice",
    example: "It took me a few days, but I finally got the hang of the new operating system.",
    examTip: "Espressione colloquiale B2 comune nelle conversazioni quotidiane (Speaking Part 4).",
    category: "idioms",
  },
  {
    id: "col-17",
    phrase: "run out of",
    translation: "esaurire / rimanere a corto di",
    definition: "to use up all of something so that there is none left",
    example: "We ran out of petrol just five miles before reaching the motorway service station.",
    examTip: "Richiede quasi sempre la preposizione 'of' e si contrappone a 'have plenty of'.",
    category: "phrasal-verbs",
  },
  {
    id: "col-18",
    phrase: "come to terms with",
    translation: "accettare / rassegnarsi a",
    definition: "to gradually accept a sad, difficult, or unpleasant situation",
    example: "It took several months for him to come to terms with losing his previous job.",
    examTip: "Struttura fissa: 'come to terms with' + gerundio o sostantivo.",
    category: "collocations",
  },
  {
    id: "col-19",
    phrase: "draw the line",
    translation: "porre un limite / stabilire un confine",
    definition: "to set a definitive limit on what you are willing to accept or do",
    example: "I enjoy helping my colleagues, but I draw the line at doing their entire workload.",
    examTip: "Collocazione metaforica classica nei saggi d'opinione (Writing Part 1).",
    category: "idioms",
  },
  {
    id: "col-20",
    phrase: "bring up",
    translation: "sollevare un argomento / menzionare",
    definition: "to mention or introduce a subject for discussion during a conversation",
    example: "I didn't want to bring up the budget issue during the general staff meeting.",
    examTip: "Ha un secondo significato: 'crescere/educare un bambino' (es. He was brought up by his grandparents).",
    category: "phrasal-verbs",
  },
  {
    id: "col-21",
    phrase: "under the impression that",
    translation: "avere l'impressione che / essere convinto che",
    definition: "believing something to be true, often when it is actually not",
    example: "I was under the impression that the registration deadline was extended to Friday.",
    examTip: "Frase preparatoria per chiarire malintesi (frequente nel Listening Part 3).",
    category: "collocations",
  },
  {
    id: "col-22",
    phrase: "catch someone's eye",
    translation: "catturare l'attenzione / lo sguardo",
    definition: "to attract someone's visual attention or interest",
    example: "A colorful vintage poster in the shop window caught her eye immediately.",
    examTip: "Distinguere da 'see eye to eye' (essere d'accordo).",
    category: "idioms",
  },
  {
    id: "col-23",
    phrase: "figure out",
    translation: "capire / risolvere (un problema)",
    definition: "to understand or solve something after thinking carefully about it",
    example: "The technicians are still trying to figure out why the backup server failed.",
    examTip: "Sinonimo più naturale e comune di 'solve' o 'understand'.",
    category: "phrasal-verbs",
  },
  {
    id: "col-24",
    phrase: "pay off",
    translation: "dare i suoi frutti / rivelarsi vantaggioso",
    definition: "to yield positive results or success after effort or investment",
    example: "All those late nights studying at the library finally paid off when the results arrived.",
    examTip: "Intransitivo nel senso di avere successo (es. 'hard work always pays off').",
    category: "phrasal-verbs",
  },
  {
    id: "col-25",
    phrase: "stand out",
    translation: "spiccare / distinguersi",
    definition: "to be much better, more noticeable, or distinct than others",
    example: "Her innovative portfolio made her stand out from all other university candidates.",
    examTip: "Forma l'aggettivo B2 'outstanding' (eccezionale/eccellente).",
    category: "phrasal-verbs",
  },
  {
    id: "col-26",
    phrase: "keep an eye on",
    translation: "tenere d'occhio / sorvegliare",
    definition: "to watch or monitor someone or something carefully",
    example: "Could you please keep an eye on my luggage while I go to buy a coffee?",
    examTip: "Molto comune nei dialoghi della prova d'ascolto (Listening Part 1).",
    category: "idioms",
  },
  {
    id: "col-27",
    phrase: "point out",
    translation: "far notare / evidenziare",
    definition: "to draw someone's attention to a particular fact or detail",
    example: "The supervisor pointed out several formatting inconsistencies in the second draft.",
    examTip: "Reporting verb utilissimo per i saggi di sintesi (Writing B2).",
    category: "phrasal-verbs",
  },
  {
    id: "col-28",
    phrase: "take after",
    translation: "assomigliare a (di famiglia)",
    definition: "to resemble a parent or older relative in appearance or character",
    example: "Lucas takes after his mother; both have a tremendous talent for playing the piano.",
    examTip: "Non confondere con 'look like' (solo estetico) o 'take care of' (prendersi cura).",
    category: "phrasal-verbs",
  },
  {
    id: "col-29",
    phrase: "in the long run",
    translation: "nel lungo periodo / alla lunga",
    definition: "over a long period of time in the future, rather than immediately",
    example: "Investing in sustainable solar panels will save significant money in the long run.",
    examTip: "Contrapposto a 'in the short term'. Molto apprezzato nei testi argomentativi.",
    category: "collocations",
  },
  {
    id: "col-30",
    phrase: "run into",
    translation: "incontrare per caso / imbattersi in",
    definition: "to meet someone unexpectedly or encounter a sudden problem",
    example: "I ran into my former English professor at the railway station yesterday morning.",
    examTip: "Sinonimo di 'bump into'. Usato anche per difficoltà: 'run into financial difficulties'.",
    category: "phrasal-verbs",
  },
];
