import type { Exercise, ReadingPassage } from "../types";

const createdAt = "2026-08-02T00:00:00.000Z";

function question(
  id: string,
  passageId: string,
  topic: string,
  prompt: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
): Exercise {
  return {
    id,
    passageId,
    type: "reading",
    section: "reading",
    topic,
    difficulty: "b2",
    level: "B2",
    question: prompt,
    instructions: "Scegli la risposta sostenuta dal testo, non solo quella plausibile.",
    options: options.map((label, index) => ({ id: String(index), label })),
    correctAnswer,
    explanation,
    examples: [],
    tags: ["reading", "b2", topic],
    estimatedTime: 90,
    source: "original",
    createdAt,
  };
}

export const b2ReadingPassages: ReadingPassage[] = [
  {
    id: "reading-library-things",
    title: "Why borrow a drill you only need once?",
    kind: "Magazine article",
    level: "B2",
    minutes: 10,
    text: [
      "Most people would never consider buying a book every time they wanted to read one, yet the same logic is rarely applied to household objects. A power drill may spend almost its entire life in a cupboard, while camping equipment is often used for only one weekend a year. This observation has inspired a growing number of ‘libraries of things’, where members borrow useful objects instead of purchasing them.",
      "The first challenge for these libraries is not finding objects but building trust. Members need to believe that equipment will be safe and available when promised. Staff therefore inspect every returned item, publish clear instructions and charge modest late fees. Some organisations also offer short workshops, so a person borrowing a sewing machine can learn how to use it confidently. These sessions have turned borrowing into a social activity rather than a simple transaction.",
      "Supporters point to obvious environmental advantages. Sharing reduces demand for newly manufactured goods and prevents rarely used products from becoming waste. The financial benefit matters too, particularly for people living in small flats or managing tight budgets. However, the model is not free of difficulties. Storage space is expensive, repairs require skilled volunteers, and popular items can be unavailable at exactly the moment everyone wants them.",
      "For this reason, successful libraries do not try to stock everything. They study local demand and choose items that are expensive enough to justify sharing but robust enough to survive repeated use. Their greatest contribution may be cultural: they encourage people to ask whether access is more useful than ownership. That question will not change every purchase, but it can make consumption more deliberate.",
    ].join("\n\n"),
    exercises: [
      question("reading-library-q1", "reading-library-things", "main idea", "What is the main purpose of the article?", ["To argue that all private ownership should end", "To explain how libraries of things work and where they face limits", "To advertise a particular tool-rental company", "To show that household tools are unsafe"], "To explain how libraries of things work and where they face limits", "The article presents the model, its benefits and its practical difficulties."),
      question("reading-library-q2", "reading-library-things", "detail", "Why do some libraries offer workshops?", ["To train professional repair workers", "To help members use borrowed equipment safely and confidently", "To persuade people to buy the objects later", "To replace the system of inspections"], "To help members use borrowed equipment safely and confidently", "The second paragraph links workshops with confidence and correct use."),
      question("reading-library-q3", "reading-library-things", "inference", "What can be inferred about popular items?", ["They are always the cheapest objects", "They may be difficult to obtain at busy times", "They are never repaired", "They are reserved for volunteers"], "They may be difficult to obtain at busy times", "The text says popular items can be unavailable exactly when many people want them."),
      question("reading-library-q4", "reading-library-things", "vocabulary in context", "In the final paragraph, ‘robust’ is closest in meaning to:", ["fashionable", "easy to replace", "strong and durable", "small enough to hide"], "strong and durable", "The object must survive repeated use, so robust means strong and durable."),
      question("reading-library-q5", "reading-library-things", "writer attitude", "What is the writer's attitude to the model?", ["Uncritically enthusiastic", "Cautiously positive", "Mostly dismissive", "Completely neutral"], "Cautiously positive", "The writer recognises clear benefits while openly discussing limitations."),
      question("reading-library-q6", "reading-library-things", "purpose", "What broader change do these libraries encourage?", ["Choosing access when ownership is unnecessary", "Avoiding all manufactured goods", "Moving to a larger home", "Learning to repair every object personally"], "Choosing access when ownership is unnecessary", "The conclusion asks whether access may be more useful than ownership."),
    ],
  },
  {
    id: "reading-four-day-week",
    title: "The four-day week: less time, better work?",
    kind: "Workplace report",
    level: "B2",
    minutes: 11,
    text: [
      "When a small software company announced that employees would work four days without losing pay, many expected productivity to fall. Instead, the first three months produced an unexpected result: projects were completed at roughly the same rate, while sick leave declined. The company did not simply remove Friday from the calendar, however. It redesigned meetings, reduced unnecessary reporting and protected long periods for focused work.",
      "This distinction is central to the debate. A shorter week cannot succeed if five days of activity are carelessly squeezed into four. Employees may feel more exhausted, and customers may struggle to reach anyone. Organisations that report positive outcomes usually prepare for months. They identify low-value tasks, train teams to make faster decisions and arrange cover so essential services remain available.",
      "The strongest argument for the model concerns recovery. Workers who have enough time for family responsibilities, exercise and rest often return with better concentration. Employers may also find recruitment easier. Yet the evidence is not equally strong in every industry. A design studio can reorganise projects more freely than a hospital or a transport network, where staffing must be continuous. Even within one company, customer support and finance teams may face different pressures.",
      "Researchers therefore warn against treating the four-day week as a universal formula. Its value lies in forcing organisations to examine how time is used. Some may adopt a permanent shorter week; others may introduce seasonal trials or flexible hours instead. The useful question is not whether Friday should disappear, but whether current routines genuinely contribute to good work.",
    ].join("\n\n"),
    exercises: [
      question("reading-week-q1", "reading-four-day-week", "main idea", "What is the writer's main argument?", ["Every organisation should close on Friday", "A shorter week works only when working practices are redesigned", "Pay should be reduced when hours are reduced", "Customer service becomes unnecessary in a shorter week"], "A shorter week works only when working practices are redesigned", "The article repeatedly distinguishes redesign from simply compressing the same work."),
      question("reading-week-q2", "reading-four-day-week", "detail", "What happened during the software company's first trial?", ["Project completion collapsed", "Employees received lower pay", "Output remained similar and sick leave fell", "All meetings were cancelled"], "Output remained similar and sick leave fell", "The first paragraph gives both results explicitly."),
      question("reading-week-q3", "reading-four-day-week", "inference", "Why might hospitals find the model harder to use?", ["Their employees dislike flexible work", "They require continuous staffing", "They have no low-value tasks", "Their work is less tiring"], "They require continuous staffing", "The third paragraph contrasts flexible projects with services that must operate continuously."),
      question("reading-week-q4", "reading-four-day-week", "vocabulary in context", "What does ‘squeezed into four’ suggest?", ["The same amount of work is compressed into less time", "Employees are given four weeks of holiday", "Four tasks are removed", "Offices become physically smaller"], "The same amount of work is compressed into less time", "The phrase warns against forcing five days of activity into four."),
      question("reading-week-q5", "reading-four-day-week", "writer attitude", "How does the writer view the available evidence?", ["It proves the model works everywhere", "It is useful but depends on context", "It should be ignored", "It applies only to hospitals"], "It is useful but depends on context", "Benefits are described, but the writer rejects a universal formula."),
      question("reading-week-q6", "reading-four-day-week", "purpose", "Why does the writer mention seasonal trials?", ["To show there are alternatives to one permanent solution", "To recommend working only in summer", "To explain how holidays are calculated", "To criticise flexible hours"], "To show there are alternatives to one permanent solution", "The final paragraph offers different ways to rethink time."),
    ],
  },
  {
    id: "reading-citizen-science",
    title: "When ordinary walkers become field researchers",
    kind: "Science feature",
    level: "B2",
    minutes: 10,
    text: [
      "Every spring, thousands of people upload photographs of insects, birds and wild flowers to citizen-science platforms. Most participants are not trained researchers. They are walkers, gardeners and students who record what they notice. Taken separately, one observation may appear unimportant; combined over many years, these records can reveal changes in migration, flowering seasons and the spread of species.",
      "Large numbers alone do not guarantee useful science. A photograph may be unclear, a location may be entered incorrectly, or an enthusiastic beginner may identify a common species as a rare one. Well-designed projects reduce these risks by asking for evidence, checking unusual records and giving volunteers short identification guides. Some platforms use software to suggest a species, but an experienced human reviewer usually confirms difficult cases.",
      "Professional scientists value these projects because no research team could visit every field and coastline each week. Volunteers provide geographical coverage that would otherwise be impossible. They also notice local detail: a gardener may recognise that butterflies arrived earlier than usual, while a commuter may record the same birds along one route for years. Such repeated observations are especially valuable.",
      "There is a benefit beyond the data. Participants often become more attentive to their surroundings and more willing to support conservation. However, project leaders must avoid presenting volunteers merely as free labour. People remain involved when they receive updates, learn new skills and understand how their observations contribute to a real question. Citizen science works best as a partnership in which curiosity is respected and quality is carefully protected.",
    ].join("\n\n"),
    exercises: [
      question("reading-science-q1", "reading-citizen-science", "main idea", "What does the article explain?", ["Why professional scientists no longer collect data", "How public observations can support research when quality is controlled", "Why software identifies every species correctly", "How to become a paid field researcher"], "How public observations can support research when quality is controlled", "The text balances the value of broad participation with verification."),
      question("reading-science-q2", "reading-citizen-science", "detail", "How do projects check unusual records?", ["They automatically delete them", "They request evidence and use experienced reviewers", "They ask the observer to pay a fee", "They publish them without review"], "They request evidence and use experienced reviewers", "These controls are listed in the second paragraph."),
      question("reading-science-q3", "reading-citizen-science", "inference", "Why are repeated observations along one route valuable?", ["They make rare species easier to invent", "They allow changes over time to be noticed", "They eliminate the need for photographs", "They guarantee perfect identification"], "They allow changes over time to be noticed", "A consistent route over years creates comparable evidence."),
      question("reading-science-q4", "reading-citizen-science", "vocabulary in context", "In paragraph three, ‘coverage’ refers to:", ["insurance against mistakes", "the number of species in one photo", "the range of places observed", "media attention"], "the range of places observed", "The contrast is with a small team being unable to visit every location."),
      question("reading-science-q5", "reading-citizen-science", "writer attitude", "What does the writer believe project leaders should do?", ["Treat volunteers as replaceable workers", "Keep research questions secret", "Show volunteers how their work matters", "Avoid giving any feedback"], "Show volunteers how their work matters", "The final paragraph says people stay involved when they understand their contribution."),
      question("reading-science-q6", "reading-citizen-science", "detail", "What role does software usually play?", ["It offers an initial identification suggestion", "It replaces every human reviewer", "It records locations without permission", "It trains professional scientists"], "It offers an initial identification suggestion", "The text says software may suggest a species, while humans confirm difficult cases."),
    ],
  },
  {
    id: "reading-urban-trees",
    title: "Can trees cool a city fairly?",
    kind: "Newspaper analysis",
    level: "B2",
    minutes: 10,
    text: [
      "On a hot afternoon, the temperature under a mature street tree can feel dramatically lower than on an unshaded pavement. Trees block direct sunlight and release water through their leaves, helping to cool the surrounding air. As heatwaves become more frequent, many cities have announced ambitious planting programmes. Counting new trees, however, is easier than creating lasting shade.",
      "Young trees require years of care before they provide significant cooling. Without enough soil, water and protection from traffic, many fail to survive. Urban planners must therefore consider maintenance from the beginning rather than spending the entire budget on planting ceremonies. In some streets, underground pipes and narrow pavements limit what can be grown, so green roofs or shaded bus stops may be more realistic.",
      "There is also a question of fairness. Wealthier neighbourhoods often already have parks and mature trees, while areas with dense housing and heavy traffic may be much hotter. Planting only where it is easiest can increase this difference. Several cities now combine temperature maps with information about age, health and income to identify residents most at risk. This approach directs investment towards need rather than appearance.",
      "Local involvement matters as well. Residents are more likely to water and protect young trees when they help select suitable locations and understand the plan. Yet consultation should not become an excuse for delay: extreme heat is already a health risk. A successful programme needs both technical expertise and public trust, measured not by the number of trees planted this year but by the amount of healthy shade that remains decades later.",
    ].join("\n\n"),
    exercises: [
      question("reading-trees-q1", "reading-urban-trees", "main idea", "What is the central message of the article?", ["Cities should plant the largest possible number of trees immediately", "Effective urban cooling requires long-term care and fair planning", "Green roofs are always better than trees", "Residents should pay for all maintenance"], "Effective urban cooling requires long-term care and fair planning", "Survival, maintenance, location and fairness are the main themes."),
      question("reading-trees-q2", "reading-urban-trees", "detail", "Why may young trees fail?", ["They create too much shade", "They may lack soil, water or protection", "They are planted only in parks", "They grow too quickly"], "They may lack soil, water or protection", "These limits are named directly in paragraph two."),
      question("reading-trees-q3", "reading-urban-trees", "inference", "What risk comes from planting only where it is easiest?", ["Trees will become too mature", "Existing inequality in heat exposure may grow", "Temperature maps will stop working", "Bus services will be cancelled"], "Existing inequality in heat exposure may grow", "The third paragraph explains that hotter, denser areas may be overlooked."),
      question("reading-trees-q4", "reading-urban-trees", "vocabulary in context", "In the final sentence, what does ‘measured’ imply?", ["A programme should be judged by lasting results", "Every tree must have the same height", "Cities should avoid collecting data", "Planting ceremonies are the main goal"], "A programme should be judged by lasting results", "The writer contrasts annual planting numbers with healthy shade decades later."),
      question("reading-trees-q5", "reading-urban-trees", "purpose", "Why are temperature maps combined with social information?", ["To choose the prettiest streets", "To locate residents who face the greatest risk", "To estimate traffic speed", "To reduce public involvement"], "To locate residents who face the greatest risk", "The combined data directs investment according to need."),
      question("reading-trees-q6", "reading-urban-trees", "writer attitude", "How does the writer view consultation?", ["Useful, but it must not cause endless delay", "Unnecessary in every situation", "More important than action", "Suitable only for wealthy areas"], "Useful, but it must not cause endless delay", "The writer values public trust but warns that heat is already dangerous."),
    ],
  },
  {
    id: "reading-repair-cafe",
    title: "A second life for broken objects",
    kind: "Human-interest feature",
    level: "B2",
    minutes: 9,
    text: [
      "On Saturday mornings, a former library fills with silent radios, torn jackets and lamps that refuse to switch on. Their owners have not come to throw them away. Volunteer engineers, electricians and sewing enthusiasts sit beside them, explaining how each object might be repaired. The repair café began as a small environmental project, but it has become a social meeting place as well.",
      "The method is deliberately collaborative. Volunteers do not simply take an item into a back room and return it working. Whenever possible, the owner watches, asks questions and performs part of the repair. This takes longer, but it builds practical confidence. A person who learns to replace a cable may be less likely to discard the next appliance that fails.",
      "Not every object can be saved. Modern products are often sealed, spare parts may be unavailable, and repairing a damaged battery can be dangerous. Volunteers are careful not to promise success and refuse work that would create a safety risk. Even an unsuccessful attempt can be useful if the owner learns why a product failed or how to choose a more repairable replacement.",
      "The café's organisers resist measuring success only by the weight of waste avoided. Retired specialists value the opportunity to pass on knowledge, newcomers practise the local language while working with others, and neighbours who might never normally meet share a table. The project changes the meaning of a broken object: it is no longer automatically rubbish, but a question that a community can investigate together.",
    ].join("\n\n"),
    exercises: [
      question("reading-repair-q1", "reading-repair-cafe", "main idea", "What makes the repair café more than a repair service?", ["It sells new appliances", "It combines practical learning with community contact", "It guarantees every repair", "It employs only retired people"], "It combines practical learning with community contact", "The article emphasises collaboration, skills and social connection."),
      question("reading-repair-q2", "reading-repair-cafe", "detail", "Why does the owner take part in the repair?", ["To make the process faster", "To learn skills and gain confidence", "To avoid speaking to volunteers", "To test dangerous batteries"], "To learn skills and gain confidence", "The second paragraph describes active participation as the core method."),
      question("reading-repair-q3", "reading-repair-cafe", "inference", "Why might a failed repair still be valuable?", ["It always produces spare parts", "It can teach the owner about failure and future choices", "It increases the weight of waste", "It allows volunteers to charge more"], "It can teach the owner about failure and future choices", "The third paragraph explicitly identifies these learning outcomes."),
      question("reading-repair-q4", "reading-repair-cafe", "vocabulary in context", "What does ‘sealed’ suggest about some modern products?", ["They are protected from rain", "They are difficult to open and repair", "They are sold with a guarantee", "They are made from paper"], "They are difficult to open and repair", "The word appears among reasons why repair may be impossible."),
      question("reading-repair-q5", "reading-repair-cafe", "writer attitude", "What is the writer's view of the café?", ["Positive about both environmental and social effects", "Doubtful that volunteers have any useful skills", "Concerned mainly about its cost", "Critical because repairs take time"], "Positive about both environmental and social effects", "Benefits are presented throughout, without hiding safety limits."),
      question("reading-repair-q6", "reading-repair-cafe", "purpose", "Why are retired specialists mentioned?", ["To show that the project preserves and shares knowledge", "To suggest younger people cannot repair anything", "To explain who owns the building", "To criticise professional training"], "To show that the project preserves and shares knowledge", "Passing on expertise is one of the wider social benefits."),
    ],
  },
  {
    id: "reading-night-trains",
    title: "The return of the night train",
    kind: "Travel feature",
    level: "B2",
    minutes: 10,
    text: [
      "For several decades, Europe's night trains appeared to be disappearing. Cheap flights connected cities quickly, while ageing sleeper services were expensive to operate. Recently, however, new routes have opened and old ones have returned. Environmental concern is one reason, but travellers are also rediscovering the appeal of leaving one city in the evening and waking in another.",
      "A night train is not automatically convenient. Tickets can be confusing because several companies may operate different parts of one journey. Private cabins are often expensive, and a seat is a poor substitute for a bed on a twelve-hour trip. Delays can also affect morning connections. Supporters argue that these problems reflect years of limited investment rather than a basic weakness of rail travel.",
      "Comparing trains with planes is more complicated than comparing journey times. A two-hour flight may require travel to a distant airport, early arrival for security and another transfer at the destination. A sleeper train usually connects city centres and replaces a night in a hotel. For some travellers, this makes the longer rail journey competitive in both time and cost.",
      "The future of night trains will depend on cooperation. Rail companies need compatible booking systems, governments must agree on cross-border timetables, and passengers need clear information when disruption occurs. Night trains are unlikely to replace aviation for every route. Their real value is offering a credible alternative on journeys where distance, comfort and timing make overnight rail practical.",
    ].join("\n\n"),
    exercises: [
      question("reading-train-q1", "reading-night-trains", "main idea", "What does the article argue about night trains?", ["They should replace every flight", "They are a useful alternative on suitable routes but need better coordination", "They are always cheaper than hotels", "They disappeared only because passengers disliked them"], "They are a useful alternative on suitable routes but need better coordination", "The conclusion limits their role while calling them a credible alternative."),
      question("reading-train-q2", "reading-night-trains", "detail", "Which problem is mentioned in paragraph two?", ["All trains have seats but no beds", "Booking can involve several operators", "Night trains never reach city centres", "Airports control rail timetables"], "Booking can involve several operators", "The text describes confusing tickets across multiple companies."),
      question("reading-train-q3", "reading-night-trains", "inference", "Why may a slower train still compete with a flight?", ["Rail passengers do not need tickets", "The total door-to-door journey and hotel cost may be favourable", "Planes cannot cross borders", "Trains always arrive early"], "The total door-to-door journey and hotel cost may be favourable", "The comparison includes airport transfers, security time and accommodation."),
      question("reading-train-q4", "reading-night-trains", "vocabulary in context", "What does ‘credible’ mean in the final paragraph?", ["believable and practical", "historic but unreliable", "free of charge", "available everywhere"], "believable and practical", "The alternative must be realistic enough for travellers to choose."),
      question("reading-train-q5", "reading-night-trains", "writer attitude", "How does the writer treat the current problems?", ["As impossible to solve", "As reasons to ban night trains", "As serious but partly linked to underinvestment", "As inventions by airlines"], "As serious but partly linked to underinvestment", "The article recognises problems and reports the investment argument."),
      question("reading-train-q6", "reading-night-trains", "purpose", "Why does the writer compare a train with a hotel night?", ["To show that cost comparisons should include what the journey replaces", "To recommend sleeping at airports", "To prove private cabins are cheap", "To describe hotel booking systems"], "To show that cost comparisons should include what the journey replaces", "A sleeper provides transport and overnight accommodation."),
    ],
  },
  {
    id: "reading-language-myths",
    title: "What bilingual minds really do",
    kind: "Psychology article",
    level: "B2",
    minutes: 11,
    text: [
      "People who use two languages are often described either as exceptionally gifted or permanently confused. Both images are misleading. Bilingual ability covers a wide range: one person may speak both languages daily, while another reads one well but rarely speaks it. Performance also changes with context. A word may come faster in the language used at work than in the language used with family.",
      "It is true that bilingual speakers sometimes take slightly longer to retrieve a particular word. This does not mean that the languages are stored in separate boxes or that one has been forgotten. Evidence suggests that both can remain active, so the brain must select the language suited to the situation. The brief delay is a consequence of managing alternatives, not proof of confusion.",
      "Claims that bilingualism automatically produces a major advantage in every kind of thinking have also been questioned. Some early studies reported stronger attention control, but later research found more varied results. Factors such as education, income, migration experience and how frequently each language is used can influence performance. A simple label such as ‘bilingual’ cannot capture all these differences.",
      "The most reliable benefits are practical and cultural. Knowing another language allows direct communication with more people and access to different communities, humour and ways of expressing ideas. These benefits do not require a person to sound like a native speaker in every situation. A more realistic view treats bilingualism not as a perfect superpower, but as a flexible skill shaped by use.",
    ].join("\n\n"),
    exercises: [
      question("reading-language-q1", "reading-language-myths", "main idea", "What is the writer trying to correct?", ["The belief that only children can learn languages", "Oversimplified ideas about bilingual ability", "The use of language at work", "Research into education"], "Oversimplified ideas about bilingual ability", "The article challenges both negative and exaggerated positive claims."),
      question("reading-language-q2", "reading-language-myths", "detail", "Why may a bilingual speaker retrieve a word more slowly?", ["Both languages may be active and require selection", "The word has disappeared from memory", "Bilingual people read less", "The languages are stored in separate boxes"], "Both languages may be active and require selection", "This explanation appears directly in paragraph two."),
      question("reading-language-q3", "reading-language-myths", "inference", "Why are later research results more varied?", ["Researchers stopped measuring attention", "Different life and language experiences affect performance", "Only income matters", "All bilingual speakers use languages identically"], "Different life and language experiences affect performance", "The third paragraph lists several factors hidden by the broad label."),
      question("reading-language-q4", "reading-language-myths", "vocabulary in context", "What does ‘capture’ mean in paragraph three?", ["physically catch", "represent accurately", "translate quickly", "remove completely"], "represent accurately", "The label cannot represent all the differences between bilingual experiences."),
      question("reading-language-q5", "reading-language-myths", "writer attitude", "Which description best matches the writer's view?", ["Bilingualism is harmful", "Bilingualism is a flexible skill with real but not magical benefits", "Bilingualism guarantees superior intelligence", "Bilingualism matters only for work"], "Bilingualism is a flexible skill with real but not magical benefits", "This is the position stated in the conclusion."),
      question("reading-language-q6", "reading-language-myths", "detail", "Which benefit does the writer consider reliable?", ["Perfect memory", "Direct access to more people and communities", "Native pronunciation in every context", "Faster performance in every mental task"], "Direct access to more people and communities", "The final paragraph calls practical and cultural benefits the most reliable."),
    ],
  },
  {
    id: "reading-community-radio",
    title: "A local voice in a global media world",
    kind: "Media report",
    level: "B2",
    minutes: 9,
    text: [
      "At a time when international platforms can deliver millions of programmes instantly, a neighbourhood radio station might appear outdated. Yet community stations continue to attract volunteers and listeners. Their strength is not technical perfection but local relevance: they announce road closures, interview independent shop owners and discuss decisions that receive little attention from national media.",
      "Producing this service is demanding. Volunteers need training in research, interviewing and broadcasting law. A friendly conversation can still spread inaccurate information, so editors check claims and make clear when a speaker is expressing an opinion. Stations must also avoid becoming controlled by the loudest local group. Inviting a range of ages and backgrounds is essential if ‘community’ is to mean more than a small circle of regular contributors.",
      "Digital technology has changed rather than destroyed local radio. Programmes can be streamed live, shared as podcasts and translated into short clips for social media. These formats allow a discussion about a local planning decision to reach residents who never listen at the scheduled time. They also make the work available to people who have moved away but retain a connection with the area.",
      "Funding remains uncertain. Advertising can cover some costs, but too much commercial influence may weaken trust. Grants are useful but temporary. Many stations survive through a mixture of membership, local sponsorship and volunteer labour. Their continued existence suggests that, even in a global information market, people still value media that recognises their street, their concerns and their voice.",
    ].join("\n\n"),
    exercises: [
      question("reading-radio-q1", "reading-community-radio", "main idea", "Why do community stations remain valuable?", ["They offer technically perfect international news", "They focus on information and voices that matter locally", "They avoid every form of digital media", "They broadcast only music"], "They focus on information and voices that matter locally", "Local relevance is identified as their main strength."),
      question("reading-radio-q2", "reading-community-radio", "detail", "Why do editors check friendly conversations?", ["Informal speakers may still give inaccurate information", "Every opinion is illegal", "Volunteers are not allowed to speak", "Local shops control the station"], "Informal speakers may still give inaccurate information", "The second paragraph warns that a friendly tone does not guarantee accuracy."),
      question("reading-radio-q3", "reading-community-radio", "inference", "What risk comes from the ‘loudest local group’?", ["The signal becomes too strong", "The station may fail to represent the wider community", "Advertising becomes cheaper", "Podcasts become longer"], "The station may fail to represent the wider community", "The writer calls for a range of ages and backgrounds."),
      question("reading-radio-q4", "reading-community-radio", "vocabulary in context", "In paragraph three, ‘retain’ is closest in meaning to:", ["keep", "sell", "forget", "measure"], "keep", "People who move away may keep a connection with the area."),
      question("reading-radio-q5", "reading-community-radio", "purpose", "Why are podcasts and clips mentioned?", ["To show digital tools can extend local radio's reach", "To prove scheduled radio has ended", "To recommend national advertising", "To replace research training"], "To show digital tools can extend local radio's reach", "The formats make local discussions available to more people and at different times."),
      question("reading-radio-q6", "reading-community-radio", "writer attitude", "How does the writer view commercial advertising?", ["It is the only acceptable funding", "It can help, but too much may reduce trust", "It has no effect on stations", "It should control programme content"], "It can help, but too much may reduce trust", "The final paragraph recognises income while warning about influence."),
    ],
  },
  {
    id: "reading-navigation",
    title: "Do we lose something when we never get lost?",
    kind: "Opinion article",
    level: "B2",
    minutes: 10,
    text: [
      "Digital maps have removed much of the uncertainty from everyday travel. A phone can calculate the fastest route, warn us about delays and even identify the correct entrance to a large building. For anyone late for an appointment or travelling alone at night, this reliability is more than a convenience. It saves time and can make unfamiliar places feel considerably safer.",
      "However, researchers who study spatial memory have asked whether constant turn-by-turn instructions change the way we notice our surroundings. When people follow a moving arrow, they can reach the destination without forming a detailed mental picture of the route. Someone who chooses streets by looking for a church tower, a park or the direction of the sun has to connect those features. That effort can make the area easier to remember later.",
      "This does not mean that everyone should switch off navigation and wander through unknown neighbourhoods. The consequences of being lost are not equal: a relaxed visitor on a free afternoon faces a different situation from a delivery driver with a schedule. Some cities are also far easier to read than others. Regular street patterns, visible landmarks and clear signs invite exploration, while confusing junctions and unsafe pedestrian routes make dependence on a screen understandable.",
      "A useful compromise is to change how we use the technology. We might study the whole route before leaving, keep the phone in a pocket for part of the journey and check it only when uncertain. We can also choose a slightly different route home when time allows. The aim is not to reject an effective tool, but to prevent convenience from turning us into passengers in places we move through every day.",
    ].join("\n\n"),
    exercises: [
      question("reading-navigation-q1", "reading-navigation", "main idea", "What question is the article mainly exploring?", ["Whether digital maps should be made illegal", "How navigation tools may affect awareness of places", "Why delivery drivers are often late", "Which city has the best street signs"], "How navigation tools may affect awareness of places", "The writer weighs the benefits of navigation against its effect on spatial attention."),
      question("reading-navigation-q2", "reading-navigation", "detail", "Why can using landmarks improve later memory?", ["It requires people to connect features of the area", "It makes every route shorter", "It removes uncertainty completely", "It guarantees that streets are safe"], "It requires people to connect features of the area", "Paragraph two explains that this mental effort helps build a picture of the route."),
      question("reading-navigation-q3", "reading-navigation", "inference", "Why does the writer compare a visitor with a delivery driver?", ["To show that getting lost has different costs in different situations", "To claim visitors never use phones", "To prove delivery work is easy", "To recommend one route for everyone"], "To show that getting lost has different costs in different situations", "The comparison supports the argument that advice must depend on context."),
      question("reading-navigation-q4", "reading-navigation", "vocabulary in context", "In paragraph three, “invite exploration” suggests that some city designs:", ["make people feel able to look around independently", "force residents to move away", "provide free guided tours", "prevent people from walking"], "make people feel able to look around independently", "Clear patterns and landmarks make exploration easier and more appealing."),
      question("reading-navigation-q5", "reading-navigation", "writer attitude", "What is the writer's attitude towards digital navigation?", ["Completely opposed", "Positive but in favour of more active use", "Uninterested in its benefits", "Convinced it damages every traveller"], "Positive but in favour of more active use", "The conclusion calls navigation effective while recommending deliberate habits."),
      question("reading-navigation-q6", "reading-navigation", "purpose", "Why does the writer suggest checking the whole route before leaving?", ["To use technology while still developing awareness of the journey", "To avoid travelling to unfamiliar places", "To memorise every street name perfectly", "To make the phone calculate a longer route"], "To use technology while still developing awareness of the journey", "This is one of the proposed compromises between convenience and attention."),
    ],
  },
  {
    id: "reading-museum-loans",
    title: "Who gets to tell an object's story?",
    kind: "Cultural report",
    level: "B2",
    minutes: 11,
    text: [
      "Museums have traditionally described themselves as guardians of objects, responsible for preserving them for future generations. Yet many collections contain items acquired during periods of colonial rule, military conflict or unequal trade. Communities connected to those objects increasingly ask not only how they were obtained, but also who has the right to display and interpret them.",
      "Permanent return is one possible response, but it is not the only one. Some institutions have developed long-term loans and shared-curatorship agreements. Under these arrangements, an object may travel between countries, while researchers and community representatives decide together how its history should be presented. Supporters argue that this approach creates relationships rather than treating a transfer as the end of a conversation.",
      "Critics point out that the word ‘loan’ can preserve the museum's legal ownership even when that ownership is precisely what is being questioned. There are practical difficulties too. Fragile objects may not survive frequent travel, smaller museums may lack suitable climate control, and insurance costs can be enormous. These concerns are real, although they can sometimes be addressed through training, funding and high-quality digital records.",
      "The debate has changed exhibition labels as well as the location of objects. Museums are more likely to explain gaps in the evidence, name the people who originally made or used an item, and include several interpretations rather than a single official account. An object does not speak for itself. The language around it determines whether visitors see a beautiful design, a scientific specimen, evidence of violence or part of a living tradition. Sharing authority therefore means sharing the power to frame the story.",
    ].join("\n\n"),
    exercises: [
      question("reading-museum-q1", "reading-museum-loans", "main idea", "What change in museum practice does the report examine?", ["A move towards shared decisions about objects and their interpretation", "A ban on preserving fragile collections", "The replacement of every object with a digital image", "A reduction in historical research"], "A move towards shared decisions about objects and their interpretation", "The article discusses returns, loans, shared curation and multiple voices."),
      question("reading-museum-q2", "reading-museum-loans", "detail", "What do supporters value about long-term loans and shared curation?", ["They can build an ongoing relationship", "They remove all transport costs", "They guarantee permanent museum ownership", "They make research unnecessary"], "They can build an ongoing relationship", "Paragraph two contrasts a continuing relationship with ending the conversation."),
      question("reading-museum-q3", "reading-museum-loans", "inference", "Why can the term ‘loan’ be controversial?", ["It may assume that the current museum remains the owner", "It describes an object as fragile", "It prevents all international travel", "It gives communities automatic legal control"], "It may assume that the current museum remains the owner", "Critics question the ownership that the word loan leaves in place."),
      question("reading-museum-q4", "reading-museum-loans", "detail", "Which practical problem is mentioned?", ["Some locations cannot provide the required environmental conditions", "Communities refuse to discuss objects", "Digital records are always inaccurate", "Every object is too large to transport"], "Some locations cannot provide the required environmental conditions", "The text refers to climate control in smaller museums."),
      question("reading-museum-q5", "reading-museum-loans", "vocabulary in context", "In the final paragraph, “frame the story” means:", ["shape how the story is understood", "put a physical frame around an object", "hide the object's appearance", "translate every label"], "shape how the story is understood", "The language surrounding an object influences the visitor's interpretation."),
      question("reading-museum-q6", "reading-museum-loans", "writer attitude", "Which statement best reflects the writer's view?", ["Location is the only issue that matters", "Sharing objects also requires sharing interpretive power", "Museums should avoid uncertain evidence", "A single official account is always clearer"], "Sharing objects also requires sharing interpretive power", "The conclusion explicitly connects shared authority with control over the story."),
    ],
  },
  {
    id: "reading-peer-teaching",
    title: "Why explaining a lesson can improve your own learning",
    kind: "Education feature",
    level: "B2",
    minutes: 9,
    text: [
      "Students often assume that the person explaining a topic must already know more than the person listening. In peer teaching, however, learners take turns helping one another understand material they are still studying themselves. The approach is used in language classes, science laboratories and professional training, sometimes through formal presentations and sometimes through short paired discussions.",
      "Preparing to explain an idea changes the way a learner reads. Instead of simply recognising familiar words, the future ‘teacher’ must identify the central point, choose an example and predict where confusion may arise. This exposes gaps that can remain hidden during silent revision. A student may believe they understand a process until a partner asks why one step is necessary.",
      "The method is not automatically effective. Confident students can dominate, while an incorrect explanation may spread if nobody checks it. Teachers therefore need to provide reliable source material, clear roles and a way to review conclusions. Asking listeners to challenge an example or summarise it in their own words is more useful than allowing one person to deliver a long speech without interruption.",
      "Peer teaching also changes the social atmosphere of a class. Questions can feel less embarrassing when everyone is expected to be both learner and explainer. At the same time, the activity should not become unpaid replacement teaching: the qualified teacher remains responsible for accuracy and for supporting students who need additional help. Used carefully, peer explanation is valuable not because students replace experts, but because expressing knowledge makes that knowledge easier to examine.",
    ].join("\n\n"),
    exercises: [
      question("reading-peer-q1", "reading-peer-teaching", "main idea", "Why can peer teaching help the student who explains?", ["Explaining requires deeper organisation and reveals gaps", "It removes the need to study source material", "It guarantees higher marks", "The listener gives every answer"], "Explaining requires deeper organisation and reveals gaps", "This is the central learning mechanism described in paragraphs two and four."),
      question("reading-peer-q2", "reading-peer-teaching", "detail", "What must a future peer teacher do while preparing?", ["Choose central ideas and anticipate confusion", "Memorise every sentence", "Avoid using examples", "Study without speaking to anyone"], "Choose central ideas and anticipate confusion", "These preparation tasks are listed in paragraph two."),
      question("reading-peer-q3", "reading-peer-teaching", "inference", "What does a partner's ‘why’ question achieve?", ["It can reveal understanding that was only superficial", "It proves the partner is wrong", "It ends the activity immediately", "It replaces the source material"], "It can reveal understanding that was only superficial", "A learner who recognises information may still be unable to justify it."),
      question("reading-peer-q4", "reading-peer-teaching", "detail", "How can teachers reduce the risk of misinformation?", ["Provide reliable material and review the conclusions", "Let only confident students speak", "Remove all challenging questions", "Avoid giving learners roles"], "Provide reliable material and review the conclusions", "Paragraph three gives these safeguards directly."),
      question("reading-peer-q5", "reading-peer-teaching", "writer attitude", "What limitation does the writer emphasise?", ["Peer teaching must not replace qualified support", "Students should never explain ideas", "Social benefits are impossible", "Only science classes can use the method"], "Peer teaching must not replace qualified support", "The final paragraph keeps responsibility with the teacher."),
      question("reading-peer-q6", "reading-peer-teaching", "purpose", "Why does the writer mention listeners summarising in their own words?", ["To give an example of active participation", "To recommend longer speeches", "To prevent students from asking questions", "To assess handwriting"], "To give an example of active participation", "The suggestion contrasts active checking with passive listening."),
    ],
  },
  {
    id: "reading-urban-wetlands",
    title: "Bringing wetlands back into the city",
    kind: "Environmental article",
    level: "B2",
    minutes: 10,
    text: [
      "For much of the twentieth century, city planners treated marshy ground as wasted space. Streams were forced into concrete channels and low-lying areas were drained for roads or buildings. This allowed rapid development, but it also removed natural places where rainwater could collect. As heavier storms become more common, some cities are now reversing that approach.",
      "An urban wetland can temporarily hold water that would otherwise enter drains all at once. Plants slow the flow, while soil absorbs part of it. The same area may provide habitat for insects and birds, cool the surrounding streets and create a public walking route. These combined benefits make wetlands attractive compared with infrastructure that performs only one function.",
      "Restoration is not as simple as digging a pond. Polluted soil may need treatment, mosquitoes must be monitored and paths have to remain accessible after rain. Residents sometimes fear that a new wetland will look untidy or reduce space for organised sport. Projects are more likely to gain support when communities help choose paths, seating and educational signs, and when planners explain how the site will change across the seasons.",
      "The strongest projects are connected to a wider water strategy. A single park cannot protect an entire city if surrounding surfaces remain covered in concrete. Green roofs, street trees, permeable pavements and improved drains all play a role. Wetlands are therefore not a magical cure, but they demonstrate a broader shift: instead of trying to move water away as fast as possible, cities are learning to make space for it.",
    ].join("\n\n"),
    exercises: [
      question("reading-wetlands-q1", "reading-urban-wetlands", "main idea", "Why are cities restoring wetlands?", ["To manage rainwater while gaining other environmental benefits", "To replace every sports field", "To increase concrete surfaces", "To remove all insects from urban areas"], "To manage rainwater while gaining other environmental benefits", "The article presents water storage together with habitat, cooling and recreation."),
      question("reading-wetlands-q2", "reading-urban-wetlands", "detail", "How does a wetland reduce pressure on drains?", ["It stores and slows water", "It prevents all rain", "It directs every stream into concrete", "It raises surrounding roads"], "It stores and slows water", "Plants, soil and temporary storage spread the flow over time."),
      question("reading-wetlands-q3", "reading-urban-wetlands", "inference", "Why are combined benefits important?", ["They allow one area to perform several useful roles", "They make maintenance unnecessary", "They guarantee public support", "They remove the need for drains"], "They allow one area to perform several useful roles", "The writer contrasts wetlands with single-purpose infrastructure."),
      question("reading-wetlands-q4", "reading-urban-wetlands", "detail", "What can improve community support?", ["Involving residents in practical design choices", "Hiding seasonal changes", "Closing every walking path", "Promising the area will always look identical"], "Involving residents in practical design choices", "Paragraph three recommends participation and clear explanation."),
      question("reading-wetlands-q5", "reading-urban-wetlands", "vocabulary in context", "In the final paragraph, a ‘magical cure’ means:", ["a complete solution on its own", "a medical treatment", "an expensive public event", "a seasonal problem"], "a complete solution on its own", "The text says wetlands must be part of a wider strategy."),
      question("reading-wetlands-q6", "reading-urban-wetlands", "writer attitude", "How does the writer view urban wetlands?", ["Useful as part of a larger change in water management", "A perfect replacement for all infrastructure", "Mostly decorative and ineffective", "Suitable only for rural locations"], "Useful as part of a larger change in water management", "The conclusion is positive but rejects the idea of a single cure."),
    ],
  },
  {
    id: "reading-gapped-community-cinema",
    title: "The cinema saved by its audience",
    kind: "Gapped text · Cambridge Part 6",
    level: "B2",
    minutes: 14,
    text: [
      "When the Palace Cinema announced that it would close, most residents assumed the building would become another supermarket. The cinema had served the town for nearly ninety years, but rising costs and declining audiences had made it difficult for the private owner to continue. [GAP 1]",
      "The group quickly discovered that affection for the building was not the same as a workable business plan. Volunteers surveyed residents, spoke to independent cinema managers and calculated how many tickets would need to be sold each week. [GAP 2] This evidence persuaded the local council to delay permission for a change of use.",
      "Raising the purchase price was the next challenge. Large donations attracted attention, but hundreds of smaller contributions created most of the total. [GAP 3] People who could not give money offered practical help instead, from legal advice to painting and electrical work.",
      "After reopening, the Palace did not try to compete directly with large entertainment centres. It showed a mixture of recent films, classics and documentaries, and invited local groups to suggest events. [GAP 4] A popular monthly programme now pairs a film with a discussion led by someone who works in the subject area.",
      "The project still faces difficult decisions. Energy bills are high, specialist repairs are expensive and volunteers cannot cover every shift. [GAP 5] The cinema therefore employs a small professional team while using volunteers for events and community activities.",
      "Its survival offers a lesson that extends beyond one building. A community campaign needs enthusiasm, but it also needs research, transparent finances and a reason for people to return after the celebration is over. [GAP 6] In the Palace's case, saving the past worked because the organisers created a useful place for the present.",
      "MISSING PARAGRAPHS",
      "A. Each person who contributed received regular updates showing exactly how the fund was growing and what remained to be achieved.",
      "B. For that reason, the organisers have resisted the idea that goodwill alone can operate a complex public venue.",
      "C. The most successful rescues do more than preserve a familiar appearance; they give the place a renewed purpose.",
      "D. A small group refused to accept that outcome and formed a cooperative with the aim of buying it.",
      "E. The programme was deliberately broader than film screenings because the organisers wanted the building to be active throughout the week.",
      "F. The results showed strong support, but also revealed that people wanted more varied events and better daytime access.",
      "G. Several national cinema chains had already offered to manage the venue without changing its programme.",
    ].join("\n\n"),
    exercises: [
      question("reading-cinema-gap-1", "reading-gapped-community-cinema", "gapped text", "Which paragraph fits GAP 1?", ["A", "B", "C", "D", "E", "F", "G"], "D", "The outcome refers back to closure and conversion; paragraph D introduces the group that challenges it."),
      question("reading-cinema-gap-2", "reading-gapped-community-cinema", "gapped text", "Which paragraph fits GAP 2?", ["A", "B", "C", "D", "E", "F", "G"], "F", "The survey and calculations produce the results described in paragraph F; 'This evidence' then refers to them."),
      question("reading-cinema-gap-3", "reading-gapped-community-cinema", "gapped text", "Which paragraph fits GAP 3?", ["A", "B", "C", "D", "E", "F", "G"], "A", "Paragraph A develops the theme of many small contributions and transparent fundraising."),
      question("reading-cinema-gap-4", "reading-gapped-community-cinema", "gapped text", "Which paragraph fits GAP 4?", ["A", "B", "C", "D", "E", "F", "G"], "E", "Paragraph E explains why the programme extends beyond ordinary screenings; the discussion events are an example."),
      question("reading-cinema-gap-5", "reading-gapped-community-cinema", "gapped text", "Which paragraph fits GAP 5?", ["A", "B", "C", "D", "E", "F", "G"], "B", "The practical limits of volunteers lead logically to the need for paid professional staff."),
      question("reading-cinema-gap-6", "reading-gapped-community-cinema", "gapped text", "Which paragraph fits GAP 6?", ["A", "B", "C", "D", "E", "F", "G"], "C", "Paragraph C states the broader lesson, which the final sentence then applies to the Palace."),
    ],
  },
  {
    id: "reading-matching-learning-habits",
    title: "Four people who changed how they learn",
    kind: "Multiple matching · Cambridge Part 7",
    level: "B2",
    minutes: 12,
    text: [
      "A — DANIEL. I used to rewrite every page of my notes because the result looked organised. The problem was that I was copying without deciding what mattered. Now I close the book and write five questions from memory. I often discover that the topic I felt most confident about is the one I cannot explain clearly. It is less comfortable, but far more useful.",
      "B — AISHA. My study plan always failed because it assumed every evening would be quiet. I now keep three versions of each task: a twenty-minute version, a ten-minute version and a two-minute version. On busy days I might only review five expressions while waiting for a bus. That small session keeps the habit alive, and I no longer treat an imperfect day as a complete failure.",
      "C — MARCO. I understand grammar rules when I read them, but I could not use them quickly in conversation. I started recording one-minute answers to simple questions, then listened for one specific feature, such as past tenses. At first hearing my own voice was embarrassing. After a few weeks, however, I noticed errors while speaking and corrected them without stopping.",
      "D — LUCY. I was preparing alone and had no idea whether my pace was realistic. A friend and I now meet online every Friday. We do not study together; we compare what we completed and choose one goal for the following week. Knowing that I will describe my progress helps me begin tasks I might otherwise postpone.",
    ].join("\n\n"),
    exercises: [
      question("reading-habits-match-1", "reading-matching-learning-habits", "multiple matching", "Who uses a very short alternative instead of abandoning study on a difficult day?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "B — Aisha", "Aisha prepares shorter versions so that a busy day does not break the habit."),
      question("reading-habits-match-2", "reading-matching-learning-habits", "multiple matching", "Who discovered that an attractive study method involved too little thinking?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "A — Daniel", "Daniel's rewritten notes looked organised, but he was copying passively."),
      question("reading-habits-match-3", "reading-matching-learning-habits", "multiple matching", "Who practises producing language under time pressure?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "C — Marco", "Marco records short spoken answers to make grammar available during conversation."),
      question("reading-habits-match-4", "reading-matching-learning-habits", "multiple matching", "Who is motivated by reporting progress to another person?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "D — Lucy", "Lucy's weekly check-in makes delayed tasks more likely to begin."),
      question("reading-habits-match-5", "reading-matching-learning-habits", "multiple matching", "Who uses difficulty as evidence that the activity is useful?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "A — Daniel", "Daniel says retrieval feels less comfortable but reveals what he cannot explain."),
      question("reading-habits-match-6", "reading-matching-learning-habits", "multiple matching", "Who became able to notice mistakes while continuing the task?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "C — Marco", "Marco eventually corrected errors while speaking without stopping."),
      question("reading-habits-match-7", "reading-matching-learning-habits", "multiple matching", "Who wanted an outside view of whether they were progressing at a suitable speed?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "D — Lucy", "Lucy says that studying alone gave her no way to judge whether her pace was realistic."),
      question("reading-habits-match-8", "reading-matching-learning-habits", "multiple matching", "Who plans for the fact that the amount of study time available will vary?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "B — Aisha", "Aisha prepares twenty-, ten- and two-minute versions of each task."),
      question("reading-habits-match-9", "reading-matching-learning-habits", "multiple matching", "Who initially felt uncomfortable with a new practice technique?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "C — Marco", "Marco found listening to recordings of his own voice embarrassing at first."),
      question("reading-habits-match-10", "reading-matching-learning-habits", "multiple matching", "Who agrees on a fresh objective with somebody else?", ["A — Daniel", "B — Aisha", "C — Marco", "D — Lucy"], "D — Lucy", "Lucy and her friend choose one goal for the following week during each check-in."),
    ],
  },
  {
    id: "reading-community-weather-stations",
    title: "Why one town measures its own weather",
    kind: "Magazine article · University course",
    level: "B2",
    minutes: 10,
    text: [
      "When residents of Bellford complained that official weather reports rarely matched conditions in their neighbourhoods, the local council initially treated the comments as ordinary conversation. The nearest professional station was only twenty kilometres away, so its forecasts appeared close enough. Yet Bellford lies between a steep ridge and a wide estuary. Cold air collects in some streets, while strong coastal winds affect others. A single regional figure could not describe these differences accurately.",
      "A group of teachers, gardeners and engineering students proposed a network of low-cost sensors. The devices would record temperature, rainfall and wind speed every ten minutes, then send the information to a public website. Before the project began, the team tested each sensor beside professional equipment. This revealed that several inexpensive models produced unreliable readings in direct sunlight, so protective covers were added and the data was checked regularly.",
      "The network soon became useful in ways its organisers had not expected. Gardeners used it to protect young plants from sudden frost, while schools compared conditions in different parts of town. During one severe storm, emergency workers identified streets where water levels were rising fastest. However, the sensors did not replace national forecasts. They added local detail to wider observations and helped residents understand why weather can vary over a short distance.",
      "The project’s greatest challenge is now keeping volunteers involved. Collecting data is less exciting once the equipment has been installed, and faulty sensors require patient investigation. To maintain interest, the team publishes a monthly story based on the figures and invites students to suggest new questions. The lesson from Bellford is not that every town needs hundreds of instruments, but that local knowledge becomes far more valuable when curiosity is combined with careful measurement.",
    ].join("\n\n"),
    exercises: [
      question("reading-weather-q1", "reading-community-weather-stations", "main idea", "What is the main purpose of the article?", ["To argue that national weather services are unnecessary", "To explain how a local measurement project developed and what it achieved", "To advertise a particular brand of sensor", "To prove that volunteers always collect perfect data"], "To explain how a local measurement project developed and what it achieved", "The article describes the reason for the network, its quality controls, its uses and its continuing challenge."),
      question("reading-weather-q2", "reading-community-weather-stations", "detail", "Why did regional reports sometimes seem inaccurate in Bellford?", ["The professional station had stopped working", "Local geographical features created different conditions", "Residents misunderstood every forecast", "The council changed the published figures"], "Local geographical features created different conditions", "The ridge and estuary cause conditions to vary across a relatively small area."),
      question("reading-weather-q3", "reading-community-weather-stations", "inference", "What does the testing process suggest about low-cost sensors?", ["They can be useful if their limitations are controlled", "They should never be used outdoors", "They are always more accurate than professional equipment", "They require no maintenance after installation"], "They can be useful if their limitations are controlled", "The team found a weakness, added covers and continued checking the data rather than rejecting the devices entirely."),
      question("reading-weather-q4", "reading-community-weather-stations", "vocabulary in context", "In the final paragraph, ‘faulty’ is closest in meaning to:", ["expensive", "not working correctly", "difficult to see", "recently installed"], "not working correctly", "The sensors need investigation because they are producing a fault or incorrect result."),
      question("reading-weather-q5", "reading-community-weather-stations", "writer attitude", "How does the writer view the project?", ["Positive about its value but realistic about the work required", "Completely convinced that it should replace official forecasting", "Doubtful that residents learned anything", "Concerned mainly about the cost of professional equipment"], "Positive about its value but realistic about the work required", "The benefits are clear, but the final paragraph openly discusses motivation and maintenance."),
      question("reading-weather-q6", "reading-community-weather-stations", "purpose", "Why does the team publish a monthly story?", ["To sell the recorded information", "To keep volunteers interested and connect figures to questions", "To prevent schools from using the website", "To avoid repairing damaged equipment"], "To keep volunteers interested and connect figures to questions", "The stories and student questions are presented as ways to maintain involvement."),
    ],
  },
  {
    id: "reading-remote-work-psychology",
    title: "The Psychology of Remote Work and Productivity",
    kind: "Psychology article",
    level: "B2",
    minutes: 12,
    text: [
      "Over the past decade, remote work has transformed from a rare perk to a mainstream employment option. Technological advances in communication and collaboration tools have made it possible for many professionals to perform their duties from home or other locations outside the traditional office. This shift has sparked considerable debate about its impact on productivity, with some studies reporting significant gains and others noting potential drawbacks.",
      "Psychological factors play a crucial role in determining the success of remote work arrangements. On the positive side, increased autonomy and flexibility often lead to higher job satisfaction and reduced stress related to commuting. However, the blurring of boundaries between work and personal life can result in longer working hours and difficulty disconnecting. Additionally, the lack of face-to-face interaction may contribute to feelings of isolation and reduced team cohesion for some employees.",
      "Research on productivity outcomes presents a mixed picture. Many remote workers report completing tasks more efficiently due to fewer office distractions and the ability to customize their work environment. Conversely, challenges such as home-based interruptions, poor ergonomic setups, and difficulties in spontaneous collaboration can hinder performance. Self-discipline and effective time management emerge as key predictors of individual success in remote settings.",
      "To maximize the benefits of remote work, both employees and organizations can adopt specific strategies. Employees benefit from establishing consistent daily routines, creating a dedicated workspace, and setting clear boundaries with household members. Employers should invest in reliable technology, provide training on virtual communication best practices, and schedule regular check-ins to maintain team alignment and address any emerging concerns promptly.",
      "As hybrid models become increasingly common, understanding the psychological dynamics of remote work remains essential. While not every individual thrives in a fully remote environment, the flexibility offered by such arrangements can lead to a more engaged and productive workforce when implemented thoughtfully. Future research will likely focus on optimizing the balance between remote and in-person work to harness the advantages of both approaches."
    ].join("\n\n"),
    exercises: [
      question("reading-remote-work-q1", "reading-remote-work-psychology", "main idea", "What is the main purpose of the article?", ["To argue that remote work should be banned in all industries", "To explain the psychological factors influencing productivity in remote work", "To promote the use of specific collaboration software", "To compare salary levels between remote and office workers"], "To explain the psychological factors influencing productivity in remote work", "Nel testo si analizzano i fattori psicologici che influenzano la produttività nel lavoro da remoto, come l'autonomia, l'isolamento e la gestione del tempo (vedi primo e secondo paragrafo)."),
      question("reading-remote-work-q2", "reading-remote-work-psychology", "detail", "According to the passage, what is a potential negative effect of blurred work-life boundaries in remote work?", ["Increased job satisfaction", "Longer working hours and difficulty disconnecting", "Improved team cohesion", "Reduced need for technology"], "Longer working hours and difficulty disconnecting", "Il secondo paragrafo afferma che la confusione tra lavoro e vita privata può portare a orari più lunghi e difficoltà a staccare."),
      question("reading-remote-work-q3", "reading-remote-work-psychology", "inference", "What can be inferred about self-discipline in remote work from the passage?", ["It is irrelevant to productivity outcomes", "It is a key predictor of individual success", "It only matters for employees with children", "It decreases over time"], "It is a key predictor of individual success", "Nel terzo paragrafo si legge che l'autodisciplina e una buona gestione del tempo sono fattori chiave per il successo individuale nel lavoro da remoto."),
      question("reading-remote-work-q4", "reading-remote-work-psychology", "vocabulary in context", "In the fourth paragraph, what does \"emerging\" most likely mean?", ["newly appearing or developing", "disappearing completely", "requiring immediate deletion", "only applicable to large companies"], "newly appearing or developing", "Il contesto parla di affrontare le preoccupazioni non appena si manifestano, quindi 'emerging' significa che stanno appena apparendo o sviluppandosi.")
    ]
  },
  {
    id: "reading-urban-rewilding",
    title: "Urban Rewilding: Bringing Nature Back to Modern Cities",
    kind: "Environmental article",
    level: "B2",
    minutes: 12,
    text: [
      "Urban rewilding refers to the process of reintroducing natural elements and ecosystems into city environments to counteract the effects of urbanization. This can include creating green roofs on buildings, establishing wildlife corridors along rivers, converting vacant lots into community gardens, and planting native species in public parks. The goal is to restore ecological functions that have been lost due to concrete development.",
      "The ecological benefits of urban rewilding are substantial. Increased biodiversity supports pollinators and other wildlife essential for healthy ecosystems. Vegetation helps filter air pollutants, reduces the urban heat island effect through shade and evapotranspiration, and improves water management by absorbing rainwater and decreasing runoff. These contributions make cities more resilient to climate change impacts.",
      "Beyond environmental advantages, urban rewilding offers significant social and psychological benefits. Access to green spaces has been linked to reduced stress, improved mental well-being, and increased physical activity among residents. Community garding projects foster social connections and provide educational opportunities about sustainable practices. Moreover, biodiverse urban areas often become attractive destinations for ecotourism, boosting local economies.",
      "Despite its potential, urban rewilding faces several challenges. Limited space in densely built areas makes large-scale projects difficult. Maintenance requirements for natural installations can be higher than expected, and some residents may perceive untidy green spaces as neglected rather than intentionally wild. Securing long-term funding and gaining public support for projects that may initially appear unconventional also pose obstacles.",
      "Looking forward, successful urban rewilding requires integration into broader city planning strategies. Policies that incentivize green infrastructure, mandatory nature-inclusive design for new developments, and partnerships between municipalities, NGOs, and citizens can drive meaningful change. Cities like Singapore and Melbourne demonstrate that even highly urbanized areas can thrive when nature is considered an essential component of urban life."
    ].join("\n\n"),
    exercises: [
      question("reading-urban-rewilding-q1", "reading-urban-rewilding", "main idea", "What is the main purpose of the article?", ["To argue that all cities should be converted into forests", "To explain the concept and benefits of urban rewilding while acknowledging its challenges", "To promote the construction of more skyscrapers in city centers", "To compare the cost of public transportation in different countries"], "To explain the concept and benefits of urban rewilding while acknowledging its challenges", "Il testo descrive il concetto di rewilding urbano, i suoi benefici ecologici e sociali, e le difficoltà che incontra (vedi tutto il brano, soprattutto primo e quarto paragrafo)."),
      question("reading-urban-rewilding-q2", "reading-urban-rewilding", "detail", "According to the passage, how does vegetation help reduce the urban heat island effect?", ["By increasing concrete surfaces", "Through shade and evapotranspiration", "By blocking all sunlight", "By generating electricity"], "Through shade and evapotranspiration", "Nel secondo paragrafo si afirma che la vegetazione riduce l'effetto isola di calore attraverso l'ombra e l'evapotraspirazione."),
      question("reading-urban-rewilding-q3", "reading-urban-rewilding", "inference", "What can be inferred about community garding projects from the passage?", ["They are only suitable for rural areas", "They foster social connections and provide educational opportunities", "They always require significant financial investment", "They are prohibited in most cities"], "They foster social connections and provide educational opportunities", "Il terzo paragrafo menziona che i progetti di orti comunitari favoriscono le relazioni sociali e offrono opportunità educative sulle pratiche sostenibili."),
      question("reading-urban-rewilding-q4", "reading-urban-rewilding", "vocabulary in context", "In the fourth paragraph, what does \"incentivize\" most likely mean?", ["To discourage through penalties", "To encourage or motivate through rewards or benefits", "To eliminate completely", "To make mandatory without exceptions"], "To encourage or motivate through rewards or benefits", "Il contesto parla di politiche che promuovono le infrastrutture verdi attraverso benefici, quindi 'incentivize' significa incoraggiare o motivare tramite premi o vantaggi.")
    ]
  },
  {
    id: "reading-digital-language-evolution",
    title: "The Evolution of Language in the Digital Era",
    kind: "Linguistics article",
    level: "B2",
    minutes: 12,
    text: [
      "The digital revolution has profoundly influenced how we use language, accelerating changes that once took centuries to occur. Instant messaging, social media platforms, and online forums favor brevity and speed, leading to the widespread adoption of abbreviations, acronyms, and novel expressions. This shift reflects the need for efficient communication in fast-paced virtual environments.",
      "One of the most visible effects of digital communication is the expansion of vocabulary through emojis, memes, and internet-specific terms. Emojis function as visual substitutes for tone and emotion, compensating for the lack of facial expressions in text-based interactions. Memes often convey complex cultural references or humorous ideas in a easily shareable format, while terms like 'selfie,' 'hashtag,' and 'viral' have entered mainstream usage.",
      "Digital communication also affects grammatical structures and syntax. Informal writing frequently relaxes traditional rules, such as capitalization and punctuation, while introducing new constructions like the intentional misspelling for emphasis or the use of periods to convey seriousness. These adaptations demonstrate language's flexibility in responding to new communicative demands.",
      "However, concerns persist about the potential drawbacks of digital language evolution. Critics argue that overreliance on informal communication may erode proficiency in formal writing and speaking, particularly among younger generations. The nuances of face-to-face interaction, such as sarcasm or subtle emotional cues, can be lost in digital exchanges, potentially leading to misunderstandings.",
      "Despite these challenges, language continues to adapt and enrich itself through digital innovation. The ability to code-switch between informal online registers and formal professional contexts has become a valuable skill. Far from deteriorating, linguistic creativity flourishes in digital spaces, suggesting that the evolution of language in the internet age represents not a decline but a transformation that enhances our communicative repertoire."
    ].join("\n\n"),
    exercises: [
      question("reading-digital-language-q1", "reading-digital-language-evolution", "main idea", "What is the main purpose of the article?", ["To argue that digital communication should be banned", "To explain how digital technology is changing vocabulary, grammar, and communication practices", "To promote the use of only formal language online", "To compare the speaking speeds of different languages"], "To explain how digital technology is changing vocabulary, grammar, and communication practices", "Il testo descrive l'impatto della tecnologia digitale sul vocabolario (emoji, meme), sulla grammatica e sulle pratiche comunicative, nonché le preoccupazioni e le opportunità che ne derivano (vedi tutto il brano)."),
      question("reading-digital-language-q2", "reading-digital-language-evolution", "detail", "According to the passage, what is one function of emojis in digital communication?", ["To replace all written words", "To compensate for the lack of facial expressions in text-based interactions", "To increase internet connection speed", "To translate languages automatically"], "To compensate for the lack of facial expressions in text-based interactions", "Nel secondo paragrafo si afferma che le emoji funzionano come sostituti visivi del tono e dell'emozione, compensando l'assenza di espressioni facciali nelle interazioni testuali."),
      question("reading-digital-language-q3", "reading-digital-language-evolution", "inference", "What can be inferred about code-switching from the passage?", ["It is unnecessary in professional settings", "It is a valuable skill that allows adaptation between informal and formal contexts", "It only applies to bilingual speakers", "It is discouraged by linguists"], "It is a valuable skill that allows adaptation between informal and formal contexts", "Nell'ultimo paragrafo si nota che la capacità di passare tra registri informali online e contesti formali professionali è diventata una competenza preziosa."),
      question("reading-digital-language-q4", "reading-digital-language-evolution", "vocabulary in context", "In the third paragraph, what does \"relaxes\" most likely mean in the context of grammatical rules?", ["makes stricter", "makes less rigid or строгий", "eliminates completely", "translates into another language"], "makes less rigid or строгий", "Il contesto indica che la scrittura informale spesso rende meno rigide le regole tradizionali como la maiuscola y la puntuación, ¡relaxes significa que se vuelven menos rigurosas o más flexibles!")
    ]
  }
];
