import { Exercise } from "../types";

export const universityExamExercises: Exercise[] = [
  {
    id: "uni-q01",
    type: "multiple-choice",
    section: "grammar",
    topic: "used to",
    difficulty: "b2",
    level: "B2",
    question: "Choose the correct option:",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "I used to live in Shanghai but now I live in Bergamo",
    options: [
      { id: "A", label: "I am used to live in Shanghai but now I live in Bergamo" },
      { id: "B", label: "I used to live in Shanghai but now I live in Bergamo" },
      { id: "C", label: "I would live in Shanghai but now I live in Bergamo" },
      { id: "D", label: "I be used to live in Shanghai but now I live in Bergamo" },
    ],
    explanation: "Usiamo 'used to' + infinito per descrivere stati o abitudini passate che non sono più vere nel presente. 'Would' si usa solo per le azioni passate, non per gli stati come 'live'.",
    tags: ["used-to", "past-habits"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q02",
    type: "multiple-choice",
    section: "grammar",
    topic: "adjective order",
    difficulty: "b2",
    level: "B2",
    question: "That's a _________________ coat.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "lovely, Italian, suede",
    options: [
      { id: "A", label: "lovely, Italian, suede" },
      { id: "B", label: "Italian, suede, lovely" },
      { id: "C", label: "suede, Italian, lovely" },
      { id: "D", label: "Italian, lovely, suede" },
    ],
    explanation: "L'ordine corretto degli aggettivi è Opinion (lovely), Origin (Italian), Material (suede).",
    tags: ["adjectives", "order"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q03",
    type: "multiple-choice",
    section: "grammar",
    topic: "second conditional",
    difficulty: "b2",
    level: "B2",
    question: "Choose the correct option:",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "I wouldn't do that if I were you.",
    options: [
      { id: "A", label: "I didn't do that if I were you." },
      { id: "B", label: "I won't do that if I were you." },
      { id: "C", label: "I wouldn't to do that if I was you." },
      { id: "D", label: "I wouldn't do that if I were you." },
    ],
    explanation: "Il Second Conditional si forma con if + past simple (were per tutte le persone, specialmente per dare consigli) e would + forma base.",
    tags: ["conditionals", "second-conditional"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q04",
    type: "multiple-choice",
    section: "grammar",
    topic: "wish",
    difficulty: "b2",
    level: "B2",
    question: "I wish _________________ to the party. It sounded great.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "I had gone",
    options: [
      { id: "A", label: "I would have gone" },
      { id: "B", label: "I went" },
      { id: "C", label: "I had gone" },
      { id: "D", label: "I didn't go" },
    ],
    explanation: "Per esprimere rimpianti su situazioni passate si usa wish + past perfect (I had gone).",
    tags: ["wish", "past-regrets"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q05",
    type: "multiple-choice",
    section: "grammar",
    topic: "future continuous",
    difficulty: "b2",
    level: "B2",
    question: "When I arrive at 7pm, Tom _____________ because he doesn't finish til 8pm.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "will still be working",
    options: [
      { id: "A", label: "will still be working" },
      { id: "B", label: "is still work" },
      { id: "C", label: "will still work" },
      { id: "D", label: "will still working" },
    ],
    explanation: "Il Future Continuous (will be + -ing) si usa per descrivere un'azione che sarà in corso in un determinato momento nel futuro.",
    tags: ["future-continuous", "future-tenses"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q06",
    type: "multiple-choice",
    section: "grammar",
    topic: "conditionals",
    difficulty: "b2",
    level: "B2",
    question: "___________ it rains a lot, we're going to go to the beach.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "Unless",
    options: [
      { id: "A", label: "In case" },
      { id: "B", label: "Whether" },
      { id: "C", label: "Unless" },
      { id: "D", label: "When" },
    ],
    explanation: "'Unless' significa 'a meno che non' (if not) ed è seguito da una frase affermativa. 'Andremo in spiaggia a meno che non piova molto'.",
    tags: ["unless", "first-conditional"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q07",
    type: "multiple-choice",
    section: "grammar",
    topic: "reported speech",
    difficulty: "b2",
    level: "B2",
    question: "Rob: \"The doctor is coming tomorrow.\"",
    instructions: "Scegli la frase corretta al discorso indiretto.",
    correctAnswer: "Rob said the doctor was coming the day after.",
    options: [
      { id: "A", label: "Rob said me the doctor is coming tomorrow." },
      { id: "B", label: "Rob said me the doctor was coming tomorrow." },
      { id: "C", label: "Rob said the doctor was coming the day after." },
      { id: "D", label: "Rob said the doctor will be come the day after." },
    ],
    explanation: "Nel reported speech, 'said' non vuole il complemento oggetto diretto senza 'to'. Il present continuous diventa past continuous ('was coming'), e 'tomorrow' diventa 'the day after' o 'the following day'.",
    tags: ["reported-speech", "backshift"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q08",
    type: "multiple-choice",
    section: "grammar",
    topic: "reported questions",
    difficulty: "b2",
    level: "B2",
    question: "Sarah: \"Can I have an ice-cream?\"",
    instructions: "Scegli la frase corretta al discorso indiretto.",
    correctAnswer: "Sarah asked if she could have an ice-cream.",
    options: [
      { id: "A", label: "Sarah asked if she could have an ice-cream." },
      { id: "B", label: "Sarah asked can she have an ice-cream?" },
      { id: "C", label: "Sarah asked if she will have an ice-cream." },
      { id: "D", label: "Sarah asked could she had an ice-cream?" },
    ],
    explanation: "Le domande indirette si formano senza invertire il verbo e il soggetto. Le domande Yes/No sono introdotte da 'if' o 'whether'. 'Can' diventa 'could'.",
    tags: ["reported-speech", "reported-questions"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q09",
    type: "multiple-choice",
    section: "grammar",
    topic: "indirect questions",
    difficulty: "b2",
    level: "B2",
    question: "Choose the correct option:",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "Do you know what time it is?",
    options: [
      { id: "A", label: "Do you know what is the time?" },
      { id: "B", label: "Do you know what time is it?" },
      { id: "C", label: "Do you know what time it is?" },
      { id: "D", label: "Do you know do you the time?" },
    ],
    explanation: "Nelle domande indirette, l'ordine delle parole dopo la parola interrogativa ('what time') deve essere l'ordine di una frase affermativa (soggetto + verbo: 'it is').",
    tags: ["indirect-questions"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q10",
    type: "multiple-choice",
    section: "grammar",
    topic: "past continuous",
    difficulty: "b2",
    level: "B2",
    question: "When the phone rang, John ________________.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "was watching TV",
    options: [
      { id: "A", label: "was watching TV" },
      { id: "B", label: "watched TV" },
      { id: "C", label: "had watched TV" },
      { id: "D", label: "had be watching TV" },
    ],
    explanation: "Si usa il Past Continuous ('was watching') per un'azione che era in corso quando è stata interrotta da un'azione più breve (Past Simple, 'rang').",
    tags: ["past-continuous", "past-tenses"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q11",
    type: "multiple-choice",
    section: "grammar",
    topic: "third conditional",
    difficulty: "b2",
    level: "B2",
    question: "Choose the correct option:",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "If I had seen Alice, I would have known the news.",
    options: [
      { id: "A", label: "If I would have seen Alice, I would have knew the news." },
      { id: "B", label: "If I had have seen Alice, I had known the news." },
      { id: "C", label: "If I had seen Alice, I would have known the news." },
      { id: "D", label: "If I have seen Alice, I will have known the news." },
    ],
    explanation: "Il Third Conditional si forma con if + past perfect, e would have + participio passato. Non si usa mai 'would' nella proposizione con 'if'.",
    tags: ["third-conditional", "conditionals"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q12",
    type: "multiple-choice",
    section: "grammar",
    topic: "modals of deduction",
    difficulty: "b2",
    level: "B2",
    question: "She's late. She _______________ the train.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "must have missed",
    options: [
      { id: "A", label: "must have missed" },
      { id: "B", label: "must have lost" },
      { id: "C", label: "must be missed" },
      { id: "D", label: "must lose" },
    ],
    explanation: "Per fare una deduzione logica sul passato si usa must + have + participio passato. Il verbo 'perdere' un mezzo di trasporto è 'miss', non 'lose'.",
    tags: ["modals-of-deduction", "past-modals"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q13",
    type: "multiple-choice",
    section: "grammar",
    topic: "modals of deduction",
    difficulty: "b2",
    level: "B2",
    question: "That __________ Louise over there. I know she's in Tokyo at the moment.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "can't be",
    options: [
      { id: "A", label: "can be" },
      { id: "B", label: "can't be" },
      { id: "C", label: "has to be" },
      { id: "D", label: "must to be" },
    ],
    explanation: "Per esprimere una certezza negativa (deduzione forte al negativo) si usa 'can't'.",
    tags: ["modals-of-deduction"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q14",
    type: "multiple-choice",
    section: "grammar",
    topic: "future predictions",
    difficulty: "b2",
    level: "B2",
    question: "Choose the correct option:",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "I'll probably go to the shop after work.",
    options: [
      { id: "A", label: "Probably I'll go to the shop after work." },
      { id: "B", label: "I'll go to the shop probably after work." },
      { id: "C", label: "I'll go to the shop after work probably." },
      { id: "D", label: "I'll probably go to the shop after work." },
    ],
    explanation: "Gli avverbi di certezza (come probably o definitely) si posizionano dopo 'will' nelle frasi affermative.",
    tags: ["will", "adverb-position"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q15",
    type: "multiple-choice",
    section: "grammar",
    topic: "present perfect vs past simple",
    difficulty: "b2",
    level: "B2",
    question: "Choose the correct option:",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "He's known Jim since he was 18 years old.",
    options: [
      { id: "A", label: "He's been knowing Jim since he was 18 years old." },
      { id: "B", label: "He knows Jim from when he was 18 years old." },
      { id: "C", label: "He's known Jim since he was 18 years old." },
      { id: "D", label: "He knew Jim since he was 18 years old." },
    ],
    explanation: "'Know' è uno stative verb e non può essere usato alla forma continua (no 'been knowing'). Si usa il Present Perfect ('s known) con 'since' per un'azione iniziata nel passato e ancora in corso.",
    tags: ["present-perfect", "stative-verbs"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q16",
    type: "multiple-choice",
    section: "grammar",
    topic: "future perfect",
    difficulty: "b2",
    level: "B2",
    question: "By this time next year _________________ five years.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "I'll have worked here for",
    options: [
      { id: "A", label: "I'll be working here for" },
      { id: "B", label: "I'll have worked here for" },
      { id: "C", label: "I'd have been worked here for" },
      { id: "D", label: "I'm working here from" },
    ],
    explanation: "Si usa il Future Perfect ('will have worked') per indicare un'azione che sarà completata o che avrà raggiunto una determinata durata (for five years) entro un preciso momento futuro ('by this time next year').",
    tags: ["future-perfect"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q17",
    type: "multiple-choice",
    section: "grammar",
    topic: "passive voice",
    difficulty: "b2",
    level: "B2",
    question: "A new hospital _________________ last year.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "was built",
    options: [
      { id: "A", label: "has been built" },
      { id: "B", label: "was built" },
      { id: "C", label: "is being built" },
      { id: "D", label: "had been being built" },
    ],
    explanation: "Con espressioni di tempo concluso al passato come 'last year', si utilizza il past simple passivo ('was built').",
    tags: ["passive", "past-simple"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q18",
    type: "multiple-choice",
    section: "grammar",
    topic: "passive voice",
    difficulty: "b2",
    level: "B2",
    question: "Your hotel room ___________ at the moment. Can you wait in the foyer?",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "is being cleaned",
    options: [
      { id: "A", label: "is been cleaned" },
      { id: "B", label: "is cleaned" },
      { id: "C", label: "is being cleaned" },
      { id: "D", label: "is be cleaned" },
    ],
    explanation: "'At the moment' richiede un tempo continuo. Per formare il present continuous passivo si usa: is/are + being + participio passato.",
    tags: ["passive", "present-continuous"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q19",
    type: "multiple-choice",
    section: "grammar",
    topic: "wish",
    difficulty: "b2",
    level: "B2",
    question: "I wish _____________ smoking.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "you would stop",
    options: [
      { id: "A", label: "you would stop" },
      { id: "B", label: "you have stopped" },
      { id: "C", label: "you would have stop" },
      { id: "D", label: "you did stop" },
    ],
    explanation: "Wish + would + infinito si usa per esprimere fastidio riguardo un comportamento altrui e il desiderio che questo cambi nel presente o nel futuro.",
    tags: ["wish", "would"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q20",
    type: "multiple-choice",
    section: "grammar",
    topic: "verb patterns",
    difficulty: "b2",
    level: "B2",
    question: "I want __________________ to the US to study next year.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "my son to go",
    options: [
      { id: "A", label: "that my son goes" },
      { id: "B", label: "my son be" },
      { id: "C", label: "my son to go" },
      { id: "D", label: "that my son go" },
    ],
    explanation: "Il verbo 'want' regge la struttura: want + oggetto + infinito con to ('want someone to do something').",
    tags: ["verb-patterns", "infinitives"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q21",
    type: "multiple-choice",
    section: "grammar",
    topic: "verb patterns",
    difficulty: "b2",
    level: "B2",
    question: "They advised __________________ a lawyer.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "us to see",
    options: [
      { id: "A", label: "us to see" },
      { id: "B", label: "that to see" },
      { id: "C", label: "us seeing" },
      { id: "D", label: "our to see" },
    ],
    explanation: "Il verbo 'advise' prende la struttura advise + persona + to-infinitive (advise someone to do something).",
    tags: ["verb-patterns", "reporting-verbs"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q22",
    type: "multiple-choice",
    section: "grammar",
    topic: "pronouns",
    difficulty: "b2",
    level: "B2",
    question: "The visitors spoke only English. ___________ spoke Italian.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "None of them",
    options: [
      { id: "A", label: "Anybody of them" },
      { id: "B", label: "No-one of them" },
      { id: "C", label: "No of them" },
      { id: "D", label: "None of them" },
    ],
    explanation: "Per indicare 'nessuno' di un gruppo specifico si usa 'None of them'. 'No-one' non si usa con 'of'.",
    tags: ["pronouns", "quantifiers"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q23",
    type: "multiple-choice",
    section: "grammar",
    topic: "comparatives",
    difficulty: "b2",
    level: "B2",
    question: "Peter speaks Chinese _________________ David does.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "more fluently than",
    options: [
      { id: "A", label: "more fluent than" },
      { id: "B", label: "fluency that" },
      { id: "C", label: "more fluently than" },
      { id: "D", label: "most fluent that" },
    ],
    explanation: "Il verbo 'speaks' richiede un avverbio (fluently). Il comparativo di un avverbio lungo si forma con 'more + avverbio + than'.",
    tags: ["comparatives", "adverbs"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q24",
    type: "multiple-choice",
    section: "grammar",
    topic: "causative",
    difficulty: "b2",
    level: "B2",
    question: "I need _____________ . They're broken.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "to get my glasses fixed",
    options: [
      { id: "A", label: "getting my glasses fixed" },
      { id: "B", label: "to get my glasses fixed" },
      { id: "C", label: "fixing my glasses" },
      { id: "D", label: "that my glasses are fixed" },
    ],
    explanation: "'Need' in questo caso richiede l'infinito. La forma causativa (per far fare qualcosa a qualcun altro) è get/have + oggetto + participio passato.",
    tags: ["causative", "verb-patterns"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q25",
    type: "multiple-choice",
    section: "grammar",
    topic: "present perfect continuous",
    difficulty: "b2",
    level: "B2",
    question: "Clare ________________________ 5 years old.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "has been playing the piano since she was",
    options: [
      { id: "A", label: "has been playing piano from" },
      { id: "B", label: "has played the piano since" },
      { id: "C", label: "has been playing the piano since she was" },
      { id: "D", label: "is playing the piano from" },
    ],
    explanation: "Un'azione iniziata nel passato che continua oggi usa il present perfect (in questo caso continuous per enfatizzare la durata). Si usa 'since' con un punto nel tempo ('she was 5').",
    tags: ["present-perfect-continuous", "since-for"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q26",
    type: "multiple-choice",
    section: "grammar",
    topic: "gerunds and infinitives",
    difficulty: "b2",
    level: "B2",
    question: "The parents watched the boys _______________.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "playing football",
    options: [
      { id: "A", label: "playing football" },
      { id: "B", label: "to play football" },
      { id: "C", label: "played football" },
      { id: "D", label: "was playing football" },
    ],
    explanation: "I verbi di percezione (watch, see, hear) seguiti da oggetto prendono la forma in -ing (per indicare che si assiste a una parte dell'azione) o l'infinito senza to (se si assiste a tutta l'azione). Qui l'unica opzione corretta è 'playing'.",
    tags: ["gerunds", "perception-verbs"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q27",
    type: "multiple-choice",
    section: "grammar",
    topic: "past perfect passive",
    difficulty: "b2",
    level: "B2",
    question: "By the time the journalists arrived the criminals _______________.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "had been arrested",
    options: [
      { id: "A", label: "have been arrested" },
      { id: "B", label: "had been arrested" },
      { id: "C", label: "was arrested" },
      { id: "D", label: "was being arrested" },
    ],
    explanation: "L'arresto è avvenuto prima dell'arrivo dei giornalisti (past perfect) ed è subito dai criminali (passivo). 'had been arrested'.",
    tags: ["passive", "past-perfect"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q28",
    type: "multiple-choice",
    section: "grammar",
    topic: "uncountable nouns",
    difficulty: "b2",
    level: "B2",
    question: "We need to hire a company to move _________ to the new house.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "the furniture",
    options: [
      { id: "A", label: "some furnitures" },
      { id: "B", label: "a furniture" },
      { id: "C", label: "the furniture" },
      { id: "D", label: "furnitures" },
    ],
    explanation: "'Furniture' in inglese è un nome non numerabile (uncountable). Non può prendere l'articolo indeterminativo 'a' o la 's' del plurale.",
    tags: ["uncountable-nouns"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q29",
    type: "multiple-choice",
    section: "grammar",
    topic: "modals of obligation",
    difficulty: "b2",
    level: "B2",
    question: "When I was at school we ___________ a uniform. We could wear jeans instead.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "didn't have to wear",
    options: [
      { id: "A", label: "must to wear" },
      { id: "B", label: "didn't have to wear" },
      { id: "C", label: "mustn't wear" },
      { id: "D", label: "can wear" },
    ],
    explanation: "Poiché c'era la possibilità di indossare jeans, non c'era l'obbligo dell'uniforme. 'Didn't have to' esprime assenza di obbligo nel passato.",
    tags: ["modals-of-obligation", "past-modals"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  },
  {
    id: "uni-q30",
    type: "multiple-choice",
    section: "grammar",
    topic: "gerunds and infinitives",
    difficulty: "b2",
    level: "B2",
    question: "I don't mind _____________ the clothes. I find it quite relaxing.",
    instructions: "Scegli l’opzione corretta.",
    correctAnswer: "ironing",
    options: [
      { id: "A", label: "to iron" },
      { id: "B", label: "ironed" },
      { id: "C", label: "iron" },
      { id: "D", label: "ironing" },
    ],
    explanation: "Il verbo 'mind' (nel senso di dispiacere o dare fastidio) è sempre seguito dal verbo in -ing.",
    tags: ["gerunds", "verb-patterns"],
    examples: [],
    estimatedTime: 45,
    source: "original",
    createdAt: "2026-08-05T00:00:00.000Z",
  }
];
