import type { Exercise, VocabularyItem } from "../types";

const createdAt = "2026-08-02T00:00:00.000Z";
type VocabularySeed = [string, string, string, string, string];

const themes: { category: string; items: VocabularySeed[] }[] = [
  {
    category: "studio e lavoro",
    items: [
      ["achievement", "traguardo", "something important that you succeed in doing", "Completing the course was a major achievement.", "accomplishment"],
      ["assignment", "compito assegnato", "a piece of work given to a student or employee", "The final assignment is due on Monday.", "task"],
      ["attendance", "frequenza/presenza", "the act of being present at a place or event", "Regular attendance is required on this course.", "presence"],
      ["compulsory", "obbligatorio", "required by a rule or law", "English is compulsory in the first year.", "mandatory"],
      ["deadline", "scadenza", "the latest time by which something must be completed", "We need to meet the deadline on Friday.", "time limit"],
      ["feedback", "riscontro", "information that helps someone improve their work", "The tutor gave detailed feedback on my essay.", "response"],
      ["hands-on", "pratico", "involving active practical experience", "The course includes hands-on laboratory work.", "practical"],
      ["insight", "comprensione profonda", "a clear and deep understanding of a situation", "The internship gave me insight into the industry.", "understanding"],
      ["internship", "tirocinio", "a period of work experience for a student or graduate", "She completed an internship at a design studio.", "placement"],
      ["meet a requirement", "soddisfare un requisito", "to achieve a condition that is officially necessary", "Applicants must meet the language requirement.", "qualify"],
      ["outcome", "risultato", "the final result of an activity or process", "The outcome depends on careful preparation.", "result"],
      ["qualification", "qualifica/titolo", "an official record showing a skill or level of education", "This qualification is recognised internationally.", "credential"],
      ["relevant", "pertinente", "directly connected with the subject or situation", "Include only relevant experience in your application.", "applicable"],
      ["workload", "carico di lavoro", "the amount of work a person has to do", "My workload increases at the end of term.", "burden"],
      ["carry out research", "svolgere una ricerca", "to perform a systematic investigation", "Students will carry out research in small groups.", "investigate"],
      ["fall behind", "rimanere indietro", "to fail to make progress as quickly as expected", "Ask for help before you fall behind with the course.", "lag"],
      ["executive", "dirigente", "an important person who makes big decisions in a company", "The executive decided to expand the business.", "director"],
      ["supervisor", "supervisore", "a person who makes sure workers are doing their job properly", "The supervisor checks the quality of the products.", "manager"],
      ["civil servant", "impiegato statale", "a person who works for a government department", "She works as a civil servant in the health department.", "government employee"],
      ["shiftwork", "lavoro a turni", "a system in which different groups of workers work at different times", "Nurses often have to do shiftwork.", "working in shifts"],
      ["flexi-time", "orario flessibile", "a system allowing employees to choose their working hours", "The company offers flexi-time to its staff.", "flexible working hours"],
      ["strike", "sciopero", "to refuse to work because of an industrial dispute", "The workers decided to go on strike for better pay.", "walkout"],
      ["get the sack", "essere licenziato", "to be dismissed from your job", "He got the sack for being consistently late.", "be fired"],
      ["made redundant", "licenziato per riduzione del personale", "thrown out, no longer needed", "Hundreds of workers were made redundant.", "laid off"],
      ["maternity leave", "congedo di maternità", "time off work before and after the birth of a baby", "She is currently on maternity leave.", "time off"],
      ["workaholic", "stacanovista", "a person who works too much and loves work", "My boss is a complete workaholic.", "work addict"],
    ],
  },
  {
    category: "viaggi e mobilità",
    items: [
      ["accommodation", "alloggio", "a place where someone can stay or live", "The price includes accommodation and breakfast.", "lodging"],
      ["commute", "tragitto casa-lavoro", "to travel regularly between home and work", "She commutes by train every morning.", "travel to work"],
      ["departure", "partenza", "the act or time of leaving a place", "Our departure was delayed by heavy snow.", "leaving"],
      ["destination", "destinazione", "the place to which someone is travelling", "Lisbon is a popular weekend destination.", "endpoint"],
      ["getaway", "breve vacanza", "a short holiday away from everyday life", "We booked a weekend getaway in the mountains.", "short break"],
      ["itinerary", "itinerario", "a detailed plan of a journey", "The guide emailed us the complete itinerary.", "route plan"],
      ["layover", "scalo", "a period spent waiting between parts of a journey", "We had a two-hour layover in Amsterdam.", "stopover"],
      ["off the beaten track", "fuori dai percorsi turistici", "far from places that many tourists visit", "The village is well off the beaten track.", "remote"],
      ["peak season", "alta stagione", "the period when the greatest number of tourists visit", "Hotels are expensive during peak season.", "high season"],
      ["picturesque", "pittoresco", "visually attractive, especially in a traditional way", "We stayed in a picturesque coastal town.", "scenic"],
      ["public transport", "trasporto pubblico", "buses, trains and other services available to everyone", "The city has reliable public transport.", "transit"],
      ["remote", "remoto/isolato", "far away from towns or other people", "They spent a week in a remote valley.", "isolated"],
      ["set off", "mettersi in viaggio", "to begin a journey", "We set off before sunrise to avoid traffic.", "depart"],
      ["sightseeing", "visita turistica", "the activity of visiting interesting places", "We spent the afternoon sightseeing.", "touring"],
      ["travel light", "viaggiare con poco bagaglio", "to take very little luggage on a journey", "It is easier to travel light on a rail trip.", "pack lightly"],
      ["unspoilt", "incontaminato", "beautiful because it has not been changed or damaged", "The island still has several unspoilt beaches.", "untouched"],
      ["drop off", "lasciare (bagagli o passeggeri)", "to take someone or something to a place and leave them there", "My husband dropped me off at the airport.", "leave"],
      ["baggage reclaim", "ritiro bagagli", "the place in an airport where you get your cases and bags", "We waited for an hour at baggage reclaim.", "luggage claim"],
      ["customs", "dogana", "the place where your bags are checked for illegal goods", "They stopped us in Customs to check our bags.", "border control"],
      ["runway", "pista (di volo)", "the long, hard surface where planes take off and land", "The plane is taxiing towards the runway.", "tarmac"],
      ["gate", "gate / uscita d'imbarco", "the place where you show your boarding pass and board the flight", "Passengers should proceed to gate 14.", "departure gate"],
      ["take off", "decollare", "when a plane leaves the ground and starts flying", "The plane will take off in ten minutes.", "depart"],
      ["land", "atterrare", "when a plane arrives on the ground after a flight", "We will land in London at 6:30 PM.", "arrive"],
      ["boarding pass", "carta d'imbarco", "a document that allows you to get on a plane", "You must show your ID and boarding pass.", "ticket"],
      ["hand luggage", "bagaglio a mano", "small bags that you can keep with you on an aircraft", "Make sure you have no liquids in your hand luggage.", "carry-on"],
      ["aisle", "corridoio (tra i sedili)", "a long narrow space between rows of seats", "I prefer an aisle seat so I can walk around.", "passageway"],
      ["cabin crew", "equipaggio di cabina", "the people whose job is to take care of passengers on a plane", "The cabin crew will serve drinks shortly.", "flight attendants"],
      ["connecting flight", "volo in coincidenza", "a flight that requires you to change planes", "I missed my connecting flight in Frankfurt.", "transfer"],
      ["long-haul", "a lungo raggio", "a journey over a long distance, usually by plane", "I always feel tired after a long-haul flight.", "long-distance"],
      ["jet lag", "jet lag (mal di fuso orario)", "tiredness caused by travelling across different time zones", "I usually suffer from terrible jet lag.", "travel fatigue"],
      ["turbulence", "turbolenza", "strong, sudden movements in the air", "Please fasten your seatbelts, we are experiencing turbulence.", "bumpiness"],
      ["fill in", "compilare", "to write information in a form or document", "I had to fill in an immigration form before landing.", "complete"],
      ["trip", "viaggio (andata e ritorno)", "a journey to a place and back again, often for a specific purpose", "We're going on a five-day trip to the mountains.", "excursion"],
      ["journey", "viaggio (tragitto)", "the time spent travelling from one place to another", "Did you have a good journey here?", "travel"],
    ],
  },
  {
    category: "ambiente, clima e geografia",
    items: [
      ["biodiversity", "biodiversità", "the variety of plant and animal life in an area", "The project aims to protect local biodiversity.", "biological variety"],
      ["carbon footprint", "impronta di carbonio", "the greenhouse gases caused by a person or activity", "Cycling can reduce your carbon footprint.", "emissions impact"],
      ["conservation", "conservazione", "the protection of nature and natural resources", "The park supports wildlife conservation.", "preservation"],
      ["drought", "siccità", "a long period with little or no rain", "The region experienced a severe drought.", "dry spell"],
      ["emissions", "emissioni", "gases released into the air", "The law sets limits on vehicle emissions.", "discharges"],
      ["endangered", "in pericolo", "at serious risk of disappearing", "The reserve protects several endangered species.", "threatened"],
      ["fossil fuel", "combustibile fossile", "coal, oil or gas formed over millions of years", "The country is reducing its use of fossil fuels.", "non-renewable fuel"],
      ["habitat", "habitat", "the natural home of a plant or animal", "Road building can destroy wildlife habitat.", "natural home"],
      ["landfill", "discarica", "a place where large amounts of waste are buried", "Too much electronic waste ends up in landfill.", "waste site"],
      ["renewable", "rinnovabile", "able to be replaced naturally", "The region invests in renewable energy.", "sustainable"],
      ["scarce", "scarso", "available only in a small amount", "Clean water is scarce in some areas.", "limited"],
      ["single-use", "monouso", "designed to be used once and then thrown away", "The café no longer provides single-use cups.", "disposable"],
      ["sustainable", "sostenibile", "able to continue without harming the environment", "The town wants a more sustainable transport system.", "eco-friendly"],
      ["tackle climate change", "affrontare il cambiamento climatico", "to take action against changes in the world's climate", "Countries must cooperate to tackle climate change.", "address global warming"],
      ["wasteful", "dispendioso/sprecone", "using more resources than necessary", "Leaving lights on all night is wasteful.", "inefficient"],
      ["wildlife", "fauna selvatica", "animals and plants living naturally in an area", "Tourists are asked not to disturb the wildlife.", "fauna"],
      ["barren", "arido/brullo", "flat land where little grows", "The landscape consists largely of barren plains.", "desolate"],
      ["glacier", "ghiacciaio", "a large river of ice that moves very slowly", "We hiked up the mountain to see the glacier.", "ice mass"],
      ["thermal spring", "sorgente termale", "hot water rising naturally from the ground", "Iceland is known for its thermal springs.", "hot spring"],
      ["geyser", "geyser", "a hole in the ground that sends out hot water and steam", "Tourists gathered to watch the geyser erupt.", "spouting spring"],
      ["gorge", "gola/canyon", "a deep, narrow valley with very steep sides", "The river flows through a deep gorge.", "canyon"],
      ["stream", "ruscello", "a small river", "We followed the stream down the mountain.", "brook"],
      ["ridge", "cresta", "a long narrow high part of a mountain", "We walked along the mountain ridge.", "crest"],
      ["summit", "vetta/cima", "the top of a mountain", "They finally reached the summit of Mount Everest.", "peak"],
      ["cape", "capo/promontorio", "a piece of land sticking out into the sea", "The Cape of Good Hope is at the southern tip.", "headland"],
      ["strait", "stretto", "a narrow stretch of sea between two areas of land", "The Strait of Gibraltar connects the Atlantic and the Mediterranean.", "channel"],
      ["tornado", "tornado", "a violently rotating column of air", "The tornado destroyed several houses in the town.", "twister"],
      ["forest fire", "incendio boschivo", "an uncontrolled fire in a wooded area", "The dry weather caused a huge forest fire.", "wildfire"],
      ["thunderstorm", "temporale", "a storm with thunder and lightning", "We stayed indoors during the heavy thunderstorm.", "storm"],
      ["sandstorm", "tempesta di sabbia", "a strong wind carrying clouds of sand", "Visibility was zero during the sandstorm.", "dust storm"],
      ["flood", "alluvione", "a large amount of water covering an area that is usually dry", "The heavy rain caused a terrible flood.", "inundation"],
      ["hurricane", "uragano", "a severe storm with very strong winds (Atlantic)", "The hurricane hit the coast of Florida.", "tropical storm"],
      ["typhoon", "tifone", "a severe storm (Northwest Pacific)", "A typhoon is approaching the Japanese coast.", "cyclone"],
      ["peak", "picco", "the pointed top of a mountain", "The mountain peak was covered in snow.", "summit"],
      ["pine", "pino", "an evergreen forest tree with leaves like needles", "The hills are covered with pine trees.", "evergreen"],
      ["vegetation", "vegetazione", "plants in general found in a particular area", "The jungle has very dense vegetation.", "flora"],
      ["slope", "pendio", "a surface which has one end higher than the other", "They skied down the steep slope.", "incline"],
      ["orchard", "frutteto", "a piece of land planted with fruit trees", "We picked apples in the local orchard.", "fruit garden"],
      ["track", "sentiero", "a rough path or minor road", "We followed a muddy track through the forest.", "path"],
      ["valley", "valle", "a low area of land between hills or mountains", "The river flows down through the valley.", "dale"],
      ["bank", "riva/sponda", "the land alongside a river or lake", "We sat on the river bank and had a picnic.", "shore"],
      ["winding", "tortuoso", "having a twisting or spiral course", "They drove along a winding mountain road.", "twisting"],
      ["muddy", "fangoso", "covered by or containing mud", "Take off your muddy boots before coming inside.", "dirty"],
      ["cultivated", "coltivato", "prepared and used for growing crops", "The cultivated land is very fertile.", "farmed"],
      ["mountainous", "montuoso", "having many mountains", "Switzerland is much more mountainous than Denmark.", "hilly"],
      ["steep", "ripido", "rising or falling sharply", "The stairs were very steep and difficult to climb.", "sheer"],
      ["gentle", "dolce/lieve", "rising or falling gradually, not steep", "The path goes up a gentle slope.", "gradual"],
    ],
  },
  {
    category: "tecnologia e media",
    items: [
      ["bias", "pregiudizio/parzialità", "an unfair preference that influences judgement", "Readers should be aware of possible media bias.", "prejudice"],
      ["breakthrough", "svolta", "an important discovery or development", "The battery design represents a major breakthrough.", "advance"],
      ["data breach", "violazione di dati", "an incident in which private information is accessed", "The company reported a serious data breach.", "security incident"],
      ["device", "dispositivo", "a piece of electronic equipment", "The app works on almost any mobile device.", "gadget"],
      ["digital literacy", "alfabetizzazione digitale", "the ability to use and evaluate digital information", "Schools increasingly teach digital literacy.", "digital competence"],
      ["headline", "titolo di giornale", "the title of a news story", "The headline did not reflect the full article.", "heading"],
      ["misleading", "fuorviante", "giving the wrong idea or impression", "The advertisement was technically true but misleading.", "deceptive"],
      ["privacy settings", "impostazioni sulla privacy", "controls that decide who can access personal information", "Review your privacy settings regularly.", "access controls"],
      ["reliable source", "fonte affidabile", "a place of information that can be trusted", "Check the claim against a reliable source.", "trusted reference"],
      ["scroll", "scorrere", "to move text or images up or down on a screen", "I stopped scrolling and read the full report.", "move through"],
      ["subscription", "abbonamento", "an arrangement to receive a service by paying regularly", "The newspaper offers a student subscription.", "membership"],
      ["user-friendly", "facile da usare", "easy for people to understand and operate", "The booking platform is remarkably user-friendly.", "intuitive"],
      ["viral", "virale", "spreading very quickly across the internet", "A short video of the event went viral.", "widely shared"],
      ["verify", "verificare", "to check that something is true or accurate", "Journalists must verify information before publication.", "confirm"],
      ["word of mouth", "passaparola", "information passed directly between people", "The café became popular through word of mouth.", "personal recommendation"],
      ["cutting-edge", "all'avanguardia", "using the newest and most advanced ideas", "The laboratory uses cutting-edge equipment.", "state-of-the-art"],
    ],
  },
  {
    category: "salute, malattie e infortuni",
    items: [
      ["balanced diet", "dieta equilibrata", "a varied way of eating that provides necessary nutrients", "A balanced diet supports long-term health.", "healthy diet"],
      ["cope with", "far fronte a", "to deal successfully with a difficult situation", "Exercise helps her cope with stress.", "manage"],
      ["exhausted", "esausto", "extremely tired", "After the night shift, he felt exhausted.", "worn out"],
      ["get into a habit", "prendere un'abitudine", "to begin doing something regularly", "Try to get into a habit of reviewing vocabulary daily.", "establish a routine"],
      ["immune system", "sistema immunitario", "the body's defence against illness", "Sleep supports the immune system.", "body defences"],
      ["nutritious", "nutriente", "containing substances needed for health", "Lentils are affordable and nutritious.", "nourishing"],
      ["overwhelmed", "sopraffatto", "unable to deal with too many demands", "She felt overwhelmed by the workload.", "overloaded"],
      ["recover", "riprendersi", "to become healthy or strong again", "It took him a week to recover from the flu.", "get better"],
      ["relieved", "sollevato", "happy because something unpleasant has ended", "I was relieved to hear the test results.", "reassured"],
      ["sedentary", "sedentario", "involving too much sitting and little exercise", "A sedentary lifestyle can affect your health.", "inactive"],
      ["sleep deprivation", "privazione del sonno", "the condition of not getting enough sleep", "Sleep deprivation reduces concentration.", "lack of sleep"],
      ["stamina", "resistenza", "the strength to continue physical or mental effort", "Long-distance running requires stamina.", "endurance"],
      ["symptom", "sintomo", "a physical sign that may indicate an illness", "A persistent cough can be a symptom of infection.", "sign"],
      ["well-being", "benessere", "the state of feeling healthy and comfortable", "Regular breaks can improve well-being.", "welfare"],
      ["work out", "allenarsi", "to exercise in order to improve fitness", "She works out three times a week.", "exercise"],
      ["wind down", "rilassarsi gradualmente", "to relax after activity or stress", "Reading helps me wind down before bed.", "unwind"],
      ["cough", "tosse", "an illness that makes you cough a lot", "He has a bad cough and a sore throat.", "hacking"],
      ["headache", "mal di testa", "a continuous pain in the head", "I took a painkiller for my headache.", "migraine"],
      ["rash", "sfogo cutaneo/eruzione", "an area of red spots on a person's skin", "She gets a rash if she eats strawberries.", "hives"],
      ["blister", "vescica/bolla", "a painful swelling on the skin, often caused by rubbing or burning", "I have a blister on my foot from these new shoes.", "swelling"],
      ["temperature", "febbre", "a body temperature that is higher than normal", "He has a temperature and aches all over.", "fever"],
      ["sunburn", "scottatura solare", "red and painful skin caused by too much sun", "Wear sunscreen to prevent severe sunburn.", "burn"],
      ["vomit", "vomitare", "to empty the contents of the stomach through the mouth", "The food poisoning made him vomit.", "throw up"],
      ["sneeze", "starnutire", "to loudly blow air out of your nose in an uncontrolled way", "Dust always makes me sneeze.", "blow"],
      ["swollen", "gonfio", "larger than normal, especially as a result of an injury", "Her ankle was completely swollen after the fall.", "puffy"],
      ["bleed", "sanguinare", "to lose blood", "Press on the wound to stop it bleeding.", "lose blood"],
      ["sore throat", "mal di gola", "a condition in which your throat is red and feels painful", "It hurts when I swallow because I have a sore throat.", "throat infection"],
      ["diarrhoea", "diarrea", "an illness in which the body's solid waste is more liquid than usual", "He caught a bug and had severe diarrhoea.", "upset stomach"],
      ["faint", "svenire", "to suddenly become unconscious for a short time", "It was so hot in the room that she fainted.", "pass out"],
      ["flu", "influenza", "a common infectious illness that causes fever and aches", "He's been in bed all week with the flu.", "influenza"],
      ["dizzy", "vertigini (avere le)", "feeling as if everything is turning around", "If you feel dizzy, you should sit down.", "giddy"],
      ["unconscious", "incosciente/svenuto", "in a state like sleep because of an injury or illness", "The cyclist was knocked unconscious in the crash.", "passed out"],
      ["allergic reaction", "reazione allergica", "a physical response to a substance you are sensitive to", "He had a severe allergic reaction to the wasp sting.", "allergy"],
      ["sprained", "slogato/storto", "injured by a sudden movement", "She sprained her ankle playing tennis.", "twisted"],
      ["blood pressure", "pressione sanguigna", "the pressure of the blood as it travels around the body", "The doctor checked my blood pressure.", "pulse"],
      ["food poisoning", "intossicazione alimentare", "an illness usually caused by eating food that contains harmful bacteria", "They got food poisoning from the undercooked chicken.", "stomach bug"],
      ["choke", "soffocare", "to stop breathing because something is blocking your throat", "The baby started to choke on a piece of food.", "suffocate"],
      ["painkiller", "antidolorifico", "a medicine used to relieve pain", "I took a painkiller for my toothache.", "aspirin"],
      ["antibiotics", "antibiotici", "medicine that kills bacteria and cures infections", "The doctor prescribed a course of antibiotics.", "medicine"],
      ["plaster", "cerotto", "a small piece of sticky material used to cover and protect a cut", "Wash the cut and put a plaster on it.", "Band-Aid"],
      ["bandage", "benda/fasciatura", "a long piece of cloth that you wrap around an injured body part", "The nurse put a bandage on my sprained wrist.", "dressing"],
      ["stitches", "punti di sutura", "short pieces of thread used to join the edges of a wound", "The cut was deep and needed five stitches.", "sutures"],
      ["pass out", "svenire (phrasal verb)", "to become unconscious", "I'd been standing for so long that I passed out.", "faint"],
      ["lie down", "sdraiarsi (phrasal verb)", "to put your body in a horizontal position", "Please lie down on the couch so I can examine you.", "rest"],
      ["throw up", "vomitare (phrasal verb)", "to empty the contents of the stomach through the mouth", "I ran to the bathroom and threw up.", "vomit"],
      ["get over", "riprendersi (phrasal verb)", "to recover from an illness or a bad experience", "It took her a long time to get over the flu.", "recover"],
      ["come round", "riprendere i sensi (phrasal verb)", "to become conscious again", "When I came round, I was lying on the floor.", "regain consciousness"],
      ["wound", "ferita", "a damaged area of the body, such as a cut or hole in the skin", "Press firmly on the wound to stop the bleeding.", "injury"],
    ],
  },
  {
    category: "società e relazioni",
    items: [
      ["belonging", "senso di appartenenza", "the feeling of being accepted as part of a group", "The club gave new residents a sense of belonging.", "connection"],
      ["bring up", "allevare/sollevare un tema", "to raise a child or introduce a subject", "She brought up an important point at the meeting.", "mention"],
      ["community", "comunità", "people who live in one area or share an interest", "The library is central to the local community.", "society"],
      ["compromise", "compromesso", "an agreement in which each side accepts less than it wanted", "Both sides reached a reasonable compromise.", "settlement"],
      ["discrimination", "discriminazione", "unfair treatment based on personal characteristics", "The policy aims to prevent workplace discrimination.", "prejudice"],
      ["fall out", "litigare", "to argue and stop being friendly", "They fell out over a minor misunderstanding.", "quarrel"],
      ["household", "nucleo familiare", "all the people living together in one home", "Energy costs affect every household.", "family unit"],
      ["inequality", "disuguaglianza", "an unfair difference between groups", "The report examines income inequality.", "disparity"],
      ["mutual", "reciproco", "felt or done equally by two or more people", "Their friendship is based on mutual respect.", "shared"],
      ["peer pressure", "pressione dei coetanei", "influence from people of the same age or group", "Peer pressure can affect young people's decisions.", "social pressure"],
      ["raise awareness", "sensibilizzare", "to increase people's knowledge of an issue", "The campaign aims to raise awareness of loneliness.", "inform the public"],
      ["rely on", "fare affidamento su", "to need or trust someone or something", "Many older residents rely on public transport.", "depend on"],
      ["supportive", "solidale", "giving encouragement or emotional help", "My colleagues were extremely supportive.", "encouraging"],
      ["take part", "partecipare", "to be involved in an activity", "More than 200 volunteers took part in the event.", "participate"],
      ["trustworthy", "degno di fiducia", "able to be trusted", "A good mediator must be trustworthy.", "reliable"],
      ["volunteer", "volontario", "someone who works without being paid", "Each volunteer receives basic training.", "unpaid helper"],
    ],
  },
  {
    category: "denaro e affari",
    items: [
      ["affordable", "accessibile economicamente", "not too expensive for ordinary people", "The city needs more affordable housing.", "reasonably priced"],
      ["budget", "bilancio", "a plan showing how much money is available and how it will be spent", "We completed the project within budget.", "spending plan"],
      ["consumer", "consumatore", "a person who buys products or services", "Consumers increasingly compare prices online.", "customer"],
      ["cost-effective", "conveniente", "producing good results without costing too much", "Online training can be a cost-effective solution.", "economical"],
      ["debt", "debito", "money that is owed to another person or organisation", "The company reduced its debt last year.", "money owed"],
      ["demand", "domanda", "the desire or need for a product or service", "Demand for electric bikes has risen.", "need"],
      ["funding", "finanziamento", "money provided for a particular purpose", "The museum received public funding.", "financial support"],
      ["income", "reddito", "money received regularly from work or investments", "Rent takes up half of his monthly income.", "earnings"],
      ["launch", "lanciare", "to introduce a new product or service", "The company will launch the app in September.", "introduce"],
      ["make a profit", "realizzare un profitto", "to earn more money than was spent", "The small business made a profit in its second year.", "earn money"],
      ["negotiate", "negoziare", "to discuss something in order to reach an agreement", "Employees negotiated more flexible hours.", "bargain"],
      ["overcharge", "far pagare troppo", "to ask someone to pay more than a fair price", "The hotel accidentally overcharged us.", "charge excessively"],
      ["refund", "rimborso", "money returned after a purchase is cancelled or unsatisfactory", "The shop offered a full refund.", "repayment"],
      ["shortage", "carenza", "a situation in which there is not enough of something", "There is a shortage of skilled workers.", "lack"],
      ["turnover", "fatturato/ricambio", "the amount of business done or the rate at which staff leave", "The retailer reported higher annual turnover.", "revenue"],
      ["custom-built", "fatto su misura", "specially made for a particular person or thing", "They sell custom-built computers.", "tailor-made"],
      ["launch", "lanciare", "to start selling a new product or service", "We plan to launch the new range next year.", "introduce"],
      ["roll out", "introdurre sul mercato", "to make a new product available for the first time", "The company rolled out an expanded range of tablets.", "release"],
      ["customer care", "servizio clienti", "looking after the customer's needs", "Personal service and customer care are our priority.", "customer service"],
      ["market research", "ricerca di mercato", "finding out beforehand what people want or need", "They didn't do any proper market research.", "analysis"],
      ["recession", "recessione", "a period of low economic activity and bad conditions for business", "The business started during a recession.", "economic decline"],
      ["potential", "potenziale", "possible when the conditions are right", "We felt there were enough potential customers.", "prospective"],
      ["order book", "registro degli ordini", "the list of orders waiting to be completed", "Our order books were full within months.", "sales record"],
      ["stiff competition", "concorrenza spietata", "other companies trying hard to be more successful than you", "You will probably face stiff competition.", "strong rivalry"],
      ["corporation", "multinazionale/corporazione", "a large company or group of companies", "The CEO of a huge corporation gave us tips.", "enterprise"],
      ["worthwhile", "che vale la pena", "valuable enough to justify the time or money spent", "The qualification was a worthwhile investment.", "beneficial"],
    ],
  },
  {
    category: "dimensioni e misure",
    items: [
      ["broad-minded", "di ampie vedute", "willing to accept other people's behaviour and beliefs", "My parents were very broad-minded.", "tolerant"],
      ["narrow-minded", "di mentalità chiusa", "not willing to accept ideas different from your own", "It's hard to discuss things with someone so narrow-minded.", "intolerant"],
      ["lengthen", "allungare", "to make something longer", "I've lengthened her skirt for her.", "make longer"],
      ["shorten", "accorciare", "to make something shorter", "The new road will shorten our journey by ten minutes.", "reduce"],
      ["shortcut", "scorciatoia", "a quicker way to get somewhere", "We took a shortcut to the station.", "quicker route"],
      ["lengthy", "lungo/interminabile", "continuing for a long time, often rather negative", "Getting a visa can be a lengthy process.", "prolonged"],
      ["heighten", "accrescere/intensificare", "to make a feeling or effect stronger", "The fog heightened the feeling of mystery.", "intensify"],
      ["faraway", "lontano", "a long way away", "He loves travelling to faraway places.", "distant"],
      ["expand", "espandere", "to get bigger in size or amount", "The business expanded considerably in the last decade.", "grow"],
      ["contract", "contrarre/restringere", "to become smaller in size or amount", "Metals expand when heated and contract when cooled.", "shrink"],
      ["shallow", "poco profondo", "not having much distance between the top and the bottom", "The children played in the shallow end of the pool.", "not deep"],
      ["horizontal", "orizzontale", "flat and level, parallel to the ground", "Draw a horizontal line across the page.", "flat"],
      ["vertical", "verticale", "standing or pointing straight up", "The shirt has vertical stripes.", "upright"],
      ["midway", "a metà strada", "in the middle of a distance or between two points", "The town is midway between Rome and Naples.", "halfway"],
      ["life-size", "a grandezza naturale", "the same size as the real person or thing", "They built a life-size statue of the king.", "full-size"],
      ["opposite", "di fronte/opposto", "on the other side of a particular area", "They sat on the opposite side of the table.", "facing"],
      ["corner", "angolo", "the place where two lines or surfaces meet", "Write your name in the bottom left-hand corner.", "angle"],
    ],
  },
  {
    category: "identità e descrizioni",
    items: [
      ["selfish", "egoista", "only thinking about yourself and not others", "It's selfish to keep it all to yourself.", "egocentric"],
      ["sensible", "assennato/ragionevole", "having common sense and being practical", "It was a sensible decision to leave early.", "practical"],
      ["stubborn", "testardo", "never changing your opinion about anything", "He is too stubborn to admit he was wrong.", "obstinate"],
      ["anxious", "ansioso", "always worried or stressed", "She feels anxious before exams.", "nervous"],
      ["bossy", "prepotente/autoritario", "always giving orders to other people", "My older sister can be very bossy.", "domineering"],
      ["charming", "affascinante", "having an attractive personality that people like", "He was a very charming and polite young man.", "attractive"],
      ["spoilt", "viziato", "getting everything you want and often easily offended", "The spoilt child cried when he didn't get his way.", "pampered"],
      ["sociable", "socievole", "friendly and enjoying being with other people", "He is a sociable person who loves parties.", "outgoing"],
      ["sensitive", "sensibile", "easily hurt or offended, or understanding others' feelings", "Don't be too harsh; he is very sensitive.", "delicate"],
      ["well-built", "di corporatura robusta", "having a large, strong body", "The rugby player was tall and well-built.", "muscular"],
      ["overweight", "sovrappeso", "heavier than is healthy", "The doctor advised him to exercise because he was overweight.", "fat"],
      ["bald", "calvo", "having little or no hair on the head", "He started going bald in his thirties.", "hairless"],
      ["slim", "snello", "thin in an attractive way", "She has a tall and slim figure.", "slender"],
      ["plain", "ordinario/banale", "not particularly attractive", "He has a plain but kind face.", "ordinary"],
      ["dark-skinned", "di carnagione scura", "having skin of a dark colour", "The actor is tall and dark-skinned.", "tanned"],
      ["mid-twenties", "sui venticinque anni", "around 24 to 26 years old", "She is in her mid-twenties.", "about twenty-five"],
      ["early thirties", "sui primi trenta (30-33)", "between 30 and 33 years old", "He achieved success in his early thirties.", "thirty-something"],
      ["late forties", "verso i cinquant'anni (47-49)", "between 47 and 49 years old", "My parents are in their late forties.", "almost fifty"],
    ],
  },
  {
    category: "nazionalità",
    items: [
      ["Pakistani", "pakistano", "from Pakistan", "He is a Pakistani student.", "from Pakistan"],
      ["Chinese", "cinese", "from China", "They love eating Chinese food.", "from China"],
      ["Dutch", "olandese", "from the Netherlands", "Amsterdam is a beautiful Dutch city.", "from the Netherlands"],
      ["Irish", "irlandese", "from Ireland", "She has an Irish accent.", "from Ireland"],
      ["Chilean", "cileno", "from Chile", "They are drinking Chilean wine.", "from Chile"],
      ["Iraqi", "iracheno", "from Iraq", "He is an Iraqi national.", "from Iraq"],
      ["Thai", "thailandese", "from Thailand", "We ordered Thai food for dinner.", "from Thailand"],
      ["Saudi", "saudita", "from Saudi Arabia", "Riyadh is the Saudi capital.", "Arabian"],
      ["Egyptian", "egiziano", "from Egypt", "We visited ancient Egyptian monuments.", "from Egypt"],
      ["Danish", "danese", "from Denmark", "The Danish countryside is very flat.", "from Denmark"],
      ["Brazilian", "brasiliano", "from Brazil", "Rio is a famous Brazilian city.", "from Brazil"],
    ],
  },
  {
    category: "pronomi e indefiniti",
    items: [
      ["whenever", "ogni volta che / in qualsiasi momento", "at any time or every time", "You can come and visit whenever you like.", "anytime"],
      ["wherever", "ovunque", "in or to any place", "Put your suitcase wherever you want.", "anywhere"],
      ["whoever", "chiunque", "the person who or any person who", "Whoever finishes first gets a piece of cake!", "anyone who"],
      ["however", "comunque (avverbio di modo)", "in whatever way or no matter how", "However she tries, she just can't remember new words.", "no matter how"],
      ["whatever", "qualunque cosa", "anything or everything", "Whatever you decide to do is fine for me.", "anything"],
      ["whichever", "qualunque (tra una scelta)", "any one from a limited set of choices", "Choose whichever earrings you like best.", "any of them"],
      ["myself", "me stesso (riflessivo)", "used by a speaker to refer to themselves as the object", "I cut myself when I was preparing dinner.", "me"],
      ["each other", "l'un l'altro (reciproco)", "used to show that each person does the same to the other", "They love each other very much.", "one another"],
    ],
  },
  {
    category: "espressioni con take",
    items: [
      ["take care of", "prendersi cura di", "to protect someone or something and provide what they need", "My mother takes good care of herself.", "look after"],
      ["take seriously", "prendere sul serio", "to consider something as important", "Katie takes gender equality very seriously.", "consider important"],
      ["take part in", "partecipare a", "to be involved in an activity", "My son always takes part in the school play.", "participate in"],
      ["take after", "assomigliare a (di famiglia)", "to look or behave like an older relative", "My husband takes after his father.", "resemble"],
      ["take responsibility", "assumersi la responsabilità", "to accept blame or the duty to deal with something", "She doesn't like taking responsibility.", "accept duty"],
      ["take your time", "fare con calma", "to not hurry", "You don't have to finish today. Take your time.", "don't hurry"],
      ["take up", "iniziare (un hobby o un'attività)", "to start doing a particular job or activity", "I'm taking up yoga because I need to relax.", "start"],
      ["take advantage of", "approfittare di", "to use a situation to get what you want", "Let's take advantage of the lovely weather.", "make use of"],
      ["take into account", "tenere in considerazione", "to consider something when judging a situation", "We didn't take the rush hour traffic into account.", "consider"],
      ["take place", "avere luogo / svolgersi", "to happen, especially after being planned", "The festival usually takes place in June.", "happen"],
    ],
  },
  {
    category: "verbi di discorso",
    items: [
      ["remind", "ricordare a qualcuno", "to make someone remember something", "Remind me to book a taxi.", "prompt"],
      ["offer", "offrire", "to ask someone if they would like you to do something", "He offered to give us a lift.", "volunteer"],
      ["persuade", "persuadere/convincere", "to make someone do something by giving good reasons", "Delia persuaded me to come tonight.", "convince"],
      ["deny", "negare", "to say that something is not true", "He denies having anything to do with it.", "reject"],
      ["regret", "pentirsi/rimpiangere", "to feel sorry about a situation or a past mistake", "I've always regretted not going to university.", "feel sorry about"],
      ["refuse", "rifiutarsi", "to say that you will not do or accept something", "He refuses to tell me why.", "decline"],
      ["accuse", "accusare", "to say that someone has done something wrong", "Harry accused Oliver of breaking his toy.", "blame"],
      ["suggest", "suggerire", "to mention an idea or possible plan for others to consider", "Molly suggested going on a cruise.", "propose"],
      ["insist", "insistere", "to say firmly or demand forcefully", "Your dad insisted on making curry for dinner.", "demand"],
      ["promise", "promettere", "to tell someone that you will certainly do something", "He promised to tidy his room.", "assure"],
      ["apologize", "scusarsi", "to tell someone that you are sorry", "Roger apologized for forgetting to call.", "say sorry"],
      ["advise", "consigliare", "to give someone advice", "His father advised him not to keep all his money in the bank.", "counsel"],
      ["admit", "ammettere", "to agree that something is true, especially unwillingly", "Ruby admitted eating all the chocolates.", "confess"],
      ["invite", "invitare", "to ask someone to go to an event", "Mike invited me to go to the theatre with him.", "ask out"],
      ["blame", "incolpare", "to say or think that someone did something wrong", "Jamie blamed us for losing the match.", "hold responsible"],
      ["complain", "lamentarsi", "to say that something is wrong or not satisfactory", "She complained that I was always late.", "grumble"],
      ["demand", "esigere", "to ask for something forcefully", "He demanded to know what she wanted.", "require"],
      ["threaten", "minacciare", "to tell someone that you will cause problems if they do not do what you want", "They threatened to take the company to court.", "intimidate"],
      ["warn", "avvertire", "to make someone realize a possible danger or problem", "They warned us not to use the local taxis.", "alert"],
    ],
  },
  {
    category: "crimine e sicurezza",
    items: [
      ["arson", "incendio doloso", "the crime of intentionally starting a fire in order to damage or destroy something", "A school was destroyed in an arson attack.", "fire-raising"],
      ["burglary", "furto con scasso", "the crime of illegally entering a building and stealing things", "He was charged with burglary.", "housebreaking"],
      ["cybercrime", "crimine informatico", "crime or illegal activity that is done using the internet", "The police have a new department for cybercrime.", "computer crime"],
      ["fraud", "frode", "the crime of getting money by deceiving people", "She was arrested for credit card fraud.", "deception"],
      ["kidnapping", "rapimento", "taking a person away illegally by force, usually to demand money", "The millionaire's son was the victim of a kidnapping.", "abduction"],
      ["mugging", "aggressione a scopo di rapina", "an act of attacking someone and stealing their money", "Police are looking for witnesses to the mugging.", "robbery"],
      ["murder", "omicidio", "the crime of intentionally killing a person", "He was convicted of murder.", "homicide"],
      ["blackmail", "ricatto", "the act of getting money by threatening to reveal a secret", "They used the photographs for blackmail.", "extortion"],
      ["smuggling", "contrabbando", "the crime of taking goods or people into or out of a country illegally", "The gang was involved in drug smuggling.", "trafficking"],
      ["shoplifting", "taccheggio", "the illegal act of taking goods from a shop without paying for them", "She was caught shoplifting in the supermarket.", "stealing"],
      ["robbery", "rapina", "the crime of stealing from somewhere or someone using force or threat", "He is in prison for armed robbery.", "theft"],
      ["court", "tribunale", "a place where trials and other legal cases happen", "The suspect will appear in court tomorrow.", "tribunal"],
      ["jury", "giuria", "a group of people chosen to decide in a court of law if someone is guilty", "The jury took two days to reach a decision.", "panel"],
      ["verdict", "verdetto", "an official decision made in a court", "The jury reached a guilty verdict.", "judgement"],
      ["prison", "prigione", "a building where criminals are forced to live as a punishment", "He was sent to prison for five years.", "jail"],
      ["arrest", "arrestare", "if the police arrest someone, they take them away to ask them about a crime", "The police arrested the suspect last night.", "detain"],
      ["sentence", "condannare", "to decide and say officially what a punishment will be", "The judge sentenced him to ten years in prison.", "punish"],
      ["surveillance", "sorveglianza", "the careful watching of a person or place", "The police kept the suspects under constant surveillance.", "observation"],
      ["manslaughter", "omicidio colposo", "the crime of killing a person without intending to do so", "She was found guilty of manslaughter.", "accidental killing"],
      ["forgery", "falsificazione", "an illegal copy of a document, painting, etc.", "The painting was exposed as a clever forgery.", "fake"],
      ["embezzlement", "appropriazione indebita", "secretly taking money that is in your care or that belongs to an organization", "The accountant was accused of embezzlement.", "stealing"],
      ["harassment", "molestia", "behaviour that annoys or upsets someone", "She complained of sexual harassment at work.", "intimidation"],
    ],
  },
  {
    category: "cultura e comunicazione",
    items: [
      ["appeal", "attrattiva", "the quality that makes something attractive or interesting", "The exhibition has broad appeal.", "attraction"],
      ["audience", "pubblico", "the people watching or listening to a performance", "The speaker encouraged questions from the audience.", "spectators"],
      ["convey", "trasmettere", "to communicate an idea, feeling or meaning", "The photograph conveys a sense of isolation.", "communicate"],
      ["critically acclaimed", "acclamato dalla critica", "praised by professional reviewers", "The series was critically acclaimed.", "highly praised"],
      ["cultural heritage", "patrimonio culturale", "traditions and objects passed through generations", "The festival celebrates the region's cultural heritage.", "legacy"],
      ["engaging", "coinvolgente", "holding someone's interest and attention", "The guide gave an engaging talk.", "captivating"],
      ["interpret", "interpretare", "to explain or understand the meaning of something", "Different readers may interpret the ending differently.", "explain"],
      ["live up to expectations", "essere all'altezza delle aspettative", "to be as good as people hoped", "The concert lived up to expectations.", "meet expectations"],
      ["moving", "commovente", "causing strong feelings, especially sadness or sympathy", "The final scene was deeply moving.", "touching"],
      ["plot", "trama", "the main events of a story", "The plot becomes more complex in the second half.", "storyline"],
      ["portray", "rappresentare", "to show a person or situation in art or writing", "The film portrays city life realistically.", "depict"],
      ["reviewer", "recensore", "a person who gives a professional opinion about a work", "One reviewer praised the lead actor.", "critic"],
      ["subtle", "sottile/non evidente", "not obvious and requiring careful attention", "The novel contains subtle humour.", "understated"],
      ["thought-provoking", "stimolante", "making people think seriously about a subject", "It was a thought-provoking documentary.", "stimulating"],
      ["venue", "luogo dell'evento", "the place where an event happens", "The theatre is an ideal venue for the festival.", "location"],
      ["word choice", "scelta lessicale", "the particular words selected to express an idea", "Formal writing requires careful word choice.", "diction"],
    ],
  },
  {
    category: "scienza e cambiamento",
    items: [
      ["accurate", "accurato", "correct and free from mistakes", "The device provides accurate measurements.", "precise"],
      ["adapt", "adattarsi", "to change in order to suit new conditions", "Species must adapt to changing temperatures.", "adjust"],
      ["assumption", "supposizione", "something accepted as true without proof", "The study challenges a common assumption.", "belief"],
      ["carry out an experiment", "condurre un esperimento", "to perform a scientific test", "The class carried out an experiment on plant growth.", "conduct a test"],
      ["evidence", "prova", "facts that support whether something is true", "There is strong evidence for the theory.", "proof"],
      ["estimate", "stimare", "to calculate approximately", "Researchers estimate that the process will take a decade.", "approximate"],
      ["ethical", "etico", "morally acceptable or correct", "The committee discussed the ethical implications.", "moral"],
      ["finding", "risultato di ricerca", "information discovered during research", "The main finding surprised the research team.", "discovery"],
      ["hypothesis", "ipotesi", "an idea that can be tested scientifically", "The results did not support the original hypothesis.", "theory"],
      ["innovation", "innovazione", "a new idea, method or product", "The award recognises innovation in clean energy.", "invention"],
      ["measure", "misurare", "to find the size, amount or degree of something", "The sensors measure air quality every hour.", "quantify"],
      ["occur", "verificarsi", "to happen", "The reaction occurs only at high temperatures.", "happen"],
      ["reliable", "affidabile", "able to be trusted or depended on", "Scientists need reliable data.", "dependable"],
      ["sample", "campione", "a small part used to represent a larger whole", "The survey used a sample of 2,000 adults.", "specimen"],
      ["significant", "significativo", "important or large enough to be noticed", "The treatment produced a significant improvement.", "considerable"],
      ["undergo", "sottoporsi/subire", "to experience a process or change", "The material undergoes testing before use.", "experience"],
    ],
  },
  {
    category: "phrasal verbs e collocazioni",
    items: [
      ["come across", "imbattersi in", "to find or meet something by chance", "I came across an interesting article yesterday.", "encounter"],
      ["come up with", "ideare", "to think of an idea or solution", "The team came up with a practical solution.", "devise"],
      ["cut down on", "ridurre", "to use or do less of something", "I am trying to cut down on sugar.", "reduce"],
      ["deal with", "gestire/affrontare", "to take action to solve a problem", "The guide explains how to deal with complaints.", "handle"],
      ["figure out", "capire/trovare una soluzione", "to understand or solve something", "We need to figure out why the system failed.", "solve"],
      ["get across", "far capire", "to communicate an idea successfully", "The speaker got her main point across clearly.", "convey"],
      ["keep up with", "stare al passo con", "to remain at the same level or speed as something", "It is difficult to keep up with rapid change.", "stay current with"],
      ["look into", "indagare", "to examine a problem or situation", "The council promised to look into the complaint.", "investigate"],
      ["make a difference", "fare la differenza", "to have an important positive effect", "Small changes can make a real difference.", "have an impact"],
      ["pay attention", "prestare attenzione", "to watch or listen carefully", "Pay attention to the time limit.", "concentrate"],
      ["point out", "far notare", "to draw attention to a fact", "The report points out several risks.", "highlight"],
      ["put off", "rimandare", "to delay an event or action", "We had to put off the meeting.", "postpone"],
      ["run out of", "rimanere senza", "to use all of something so none is left", "We ran out of time before the final question.", "exhaust"],
      ["set up", "organizzare/fondare", "to arrange or establish something", "They set up a community repair club.", "establish"],
      ["take into account", "tenere conto di", "to consider a fact when making a decision", "The plan must take costs into account.", "consider"],
      ["turn down", "rifiutare/abbassare", "to refuse an offer or reduce volume", "She turned down the job offer.", "reject"],
    ],
  },
  {
    category: "casa e città",
    items: [
      ["amenities", "servizi/strutture", "useful facilities available in a place", "The neighbourhood has excellent public amenities.", "facilities"],
      ["commute", "tragitto casa-lavoro", "the regular journey between home and work", "Her daily commute takes about forty minutes.", "journey to work"],
      ["congestion", "congestione/traffico", "a situation in which roads or places are too crowded", "A new tram line could reduce traffic congestion.", "overcrowding"],
      ["derelict", "abbandonato e in rovina", "in very poor condition because it is no longer used", "The council converted a derelict factory into flats.", "neglected"],
      ["household", "nucleo familiare/domestico", "all the people living together in one home", "Energy use varies considerably between households.", "home"],
      ["landmark", "punto di riferimento", "a building or place that is easily recognised", "The clock tower is a familiar local landmark.", "notable site"],
      ["lively", "vivace", "full of energy, activity and excitement", "The square becomes lively in the evening.", "vibrant"],
      ["outskirts", "periferia", "the outer areas of a town or city", "They moved to a quieter house on the outskirts.", "edge of town"],
      ["pedestrian", "pedone", "a person travelling on foot rather than in a vehicle", "The redesign makes the centre safer for pedestrians.", "walker"],
      ["premises", "locali/sede", "a building and land used by an organisation", "The company moved to larger premises last year.", "property"],
      ["renovate", "ristrutturare", "to repair and improve an old building", "They plan to renovate the public swimming pool.", "restore"],
      ["residential", "residenziale", "mainly used for homes rather than business", "Heavy vehicles are banned from the residential area.", "housing-related"],
      ["spacious", "spazioso", "having plenty of room inside", "The flat is bright and surprisingly spacious.", "roomy"],
      ["tenant", "inquilino", "someone who pays rent to use a property", "The landlord must inform every tenant about the repairs.", "renter"],
      ["urban planning", "pianificazione urbana", "the process of designing how a town develops", "Good urban planning includes parks and public transport.", "city planning"],
      ["vacant", "libero/non occupato", "not currently occupied or being used", "Several vacant shops became temporary art studios.", "empty"],
    ],
  },
  {
    category: "legge e cittadinanza",
    items: [
      ["authority", "autorità", "an organisation or person with official power", "The local authority approved the safety plan.", "official body"],
      ["ban", "divieto/vietare", "an official rule that prevents an activity", "The city introduced a ban on single-use plastics.", "prohibition"],
      ["comply", "rispettare/adempiere", "to act according to a rule or request", "Businesses must comply with the new regulations.", "obey"],
      ["consent", "consenso", "permission for something to happen", "Researchers need written consent from each participant.", "permission"],
      ["entitlement", "diritto spettante", "a legal right to receive or do something", "Employees have an entitlement to paid leave.", "right"],
      ["enforce", "far rispettare", "to make sure that a law or rule is obeyed", "It is difficult to enforce the rule without inspections.", "apply"],
      ["evidence", "prova/evidenza", "information that supports whether something is true", "The decision must be based on reliable evidence.", "proof"],
      ["fine", "multa", "money paid as punishment for breaking a rule", "Drivers may receive a fine for parking there.", "penalty"],
      ["fraud", "frode", "the crime of gaining money through deception", "The bank improved its systems for detecting fraud.", "deception"],
      ["guideline", "linea guida", "official advice about how something should be done", "The organisation published new safety guidelines.", "recommendation"],
      ["mandatory", "obbligatorio", "required by a law or rule", "Protective equipment is mandatory in this area.", "compulsory"],
      ["policy", "politica/regolamento", "an agreed plan used by an organisation or government", "The school revised its mobile phone policy.", "official approach"],
      ["privacy", "riservatezza/privacy", "the right to keep personal information protected", "Users are increasingly concerned about online privacy.", "confidentiality"],
      ["regulation", "normativa", "an official rule controlling an activity", "The regulation applies to companies of every size.", "rule"],
      ["rights", "diritti", "legal or moral freedoms that people should have", "The campaign informs tenants about their rights.", "freedoms"],
      ["witness", "testimone", "a person who sees an event and can describe it", "Police asked witnesses to contact them.", "observer"],
    ],
  },
  {
    category: "emozioni e personalità",
    items: [
      ["ambitious", "ambizioso", "determined to achieve important goals", "She is ambitious but realistic about the time required.", "aspiring"],
      ["anxious", "ansioso", "worried or nervous about something uncertain", "He felt anxious before the job interview.", "uneasy"],
      ["considerate", "premuroso", "careful not to inconvenience or upset others", "It was considerate of you to warn the neighbours.", "thoughtful"],
      ["determined", "determinato", "having made a firm decision to succeed", "They were determined to finish the project on time.", "resolute"],
      ["disappointed", "deluso", "unhappy because something was worse than expected", "Fans were disappointed by the cancelled concert.", "dissatisfied"],
      ["embarrassed", "imbarazzato", "uncomfortable because of a social mistake or attention", "I was embarrassed when I forgot her name.", "self-conscious"],
      ["frustrated", "frustrato", "annoyed because progress is blocked", "Users became frustrated by the complicated form.", "discouraged"],
      ["generous", "generoso", "willing to give time, help or money", "Volunteers were generous with their time.", "giving"],
      ["grateful", "grato", "feeling thankful for help or kindness", "We are grateful for your detailed feedback.", "thankful"],
      ["open-minded", "di mentalità aperta", "willing to consider unfamiliar ideas", "A good discussion requires open-minded participants.", "receptive"],
      ["overwhelmed", "sopraffatto", "feeling unable to manage too many demands", "She felt overwhelmed by the amount of information.", "overloaded"],
      ["patient", "paziente", "able to wait or deal with difficulty calmly", "The tutor was patient with complete beginners.", "tolerant"],
      ["reliable", "affidabile", "consistently doing what is expected", "We need a reliable person to manage the bookings.", "dependable"],
      ["reluctant", "riluttante", "unwilling and slightly hesitant to do something", "He was reluctant to speak before seeing the evidence.", "hesitant"],
      ["sensible", "assennato", "showing practical and reasonable judgement", "Taking a short break would be a sensible choice.", "reasonable"],
      ["sympathetic", "comprensivo", "showing understanding of another person's difficulty", "The manager was sympathetic to her situation.", "understanding"],
    ],
  },
  {
    category: "cibo e consumi",
    items: [
      ["appetite", "appetito", "the desire to eat food", "A long walk gave everyone a healthy appetite.", "hunger"],
      ["consume", "consumare", "to use, eat or drink a resource or product", "The average household consumes less energy than before.", "use"],
      ["convenience", "comodità", "the quality of being easy and suitable to use", "Online shopping offers convenience but creates more packaging.", "ease"],
      ["customer loyalty", "fedeltà del cliente", "the tendency to keep buying from the same business", "Good service can build customer loyalty.", "repeat custom"],
      ["disposable", "usa e getta", "designed to be thrown away after use", "The café replaced disposable cups with reusable ones.", "single-use"],
      ["ethical", "etico", "morally responsible and fair", "Many shoppers want more ethical supply chains.", "responsible"],
      ["expiry date", "data di scadenza", "the date after which a product should not be used", "Check the expiry date before buying fresh food.", "use-by date"],
      ["ingredient", "ingrediente", "one of the foods or substances used in a product", "The sauce contains only four ingredients.", "component"],
      ["locally sourced", "di provenienza locale", "obtained from producers near the place of sale", "The restaurant uses locally sourced vegetables.", "locally produced"],
      ["nutritious", "nutriente", "containing substances needed for good health", "Beans are affordable and highly nutritious.", "nourishing"],
      ["packaging", "imballaggio", "material used to protect and present a product", "The company reduced unnecessary packaging.", "wrapping"],
      ["portion", "porzione", "an amount of food served to one person", "The portions were generous without creating waste.", "serving"],
      ["refund", "rimborso", "money returned after a product is taken back", "Customers can request a full refund within fourteen days.", "repayment"],
      ["retailer", "rivenditore", "a business that sells directly to consumers", "The retailer introduced refill stations in every branch.", "seller"],
      ["sustainable", "sostenibile", "able to continue without causing serious environmental harm", "Seasonal food can be a more sustainable choice.", "environmentally viable"],
      ["value for money", "buon rapporto qualità-prezzo", "good quality compared with the price paid", "The basic model offers excellent value for money.", "worth the price"],
    ],
  },
  {
    category: "tempo libero e sport",
    items: [
      ["amateur", "dilettante", "someone who does an activity for enjoyment rather than payment", "The race welcomes both professional and amateur runners.", "non-professional"],
      ["audience", "pubblico", "the people watching or listening to a performance", "The speaker encouraged questions from the audience.", "spectators"],
      ["challenge", "sfida", "a difficult activity that tests ability", "Completing the route was a rewarding challenge.", "test"],
      ["competitive", "competitivo", "wanting to win or be more successful than others", "The league is competitive but still friendly.", "rivalrous"],
      ["endurance", "resistenza", "the ability to continue a demanding activity", "Long-distance cycling requires physical endurance.", "stamina"],
      ["entertainment", "intrattenimento", "activities designed to amuse or interest people", "The festival provides free family entertainment.", "amusement"],
      ["fixture", "incontro programmato", "a sports match arranged for a particular date", "Saturday's fixture was postponed because of rain.", "scheduled match"],
      ["leisure", "tempo libero", "time when a person is free from work or duties", "The centre offers several leisure activities.", "free time"],
      ["membership", "iscrizione/appartenenza", "the state of belonging to a club or organisation", "Annual membership includes access to the pool.", "subscription"],
      ["opponent", "avversario", "a person or team competing against another", "She congratulated her opponent after the match.", "rival"],
      ["outdoor pursuit", "attività all'aperto", "a recreational activity done outside", "Hiking is the region's most popular outdoor pursuit.", "outdoor activity"],
      ["performance", "prestazione/spettacolo", "how well someone does or an event presented to viewers", "The team analysed its performance after the game.", "display"],
      ["recreation", "svago", "activity done for enjoyment and relaxation", "The lake is used for recreation as well as fishing.", "leisure"],
      ["spectator", "spettatore", "someone who watches a sport or public event", "Thousands of spectators lined the route.", "viewer"],
      ["take part", "partecipare", "to join and be involved in an activity", "More than two hundred residents took part in the survey.", "participate"],
      ["venue", "sede dell'evento", "the place where an organised event happens", "The venue is within walking distance of the station.", "location"],
    ],
  },
  {
    category: "programma universitario",
    items: [
      ["put forward a proposal", "avanzare una proposta", "to present an idea for other people to consider", "The research team put forward a proposal for a new survey.", "suggest a plan"],
      ["custom-built", "costruito su misura", "designed and made for a particular person or purpose", "The laboratory uses custom-built recording equipment.", "made to order"],
      ["roll out", "introdurre gradualmente", "to introduce a product or service across an area or organisation", "The company will roll out the service in three regions.", "introduce gradually"],
      ["customer care", "assistenza clienti", "the help and attention a business gives its customers", "Reliable customer care can improve a company's reputation.", "customer support"],
      ["market research", "ricerca di mercato", "the study of what customers need and are likely to buy", "The firm carried out market research before changing the product.", "consumer research"],
      ["potential customer", "cliente potenziale", "a person who may buy a product or service", "The advert is aimed at potential customers under thirty.", "prospective buyer"],
      ["order book", "portafoglio ordini", "a record of the orders a company has received", "The factory has a full order book until December.", "orders received"],
      ["face stiff competition", "affrontare una forte concorrenza", "to compete against powerful or successful rivals", "Independent shops face stiff competition from online retailers.", "meet strong rivalry"],
      ["launch a product", "lanciare un prodotto", "to make a new product available for the first time", "They plan to launch the product at an international trade fair.", "bring to market"],
      ["economic recession", "recessione economica", "a period when economic activity and business decline", "The company reduced investment during the economic recession.", "economic downturn"],
      ["work shifts", "lavorare a turni", "to work during different scheduled periods of the day or night", "Hospital staff often work shifts to provide continuous care.", "work a rota"],
      ["go on strike", "scioperare", "to stop working as an organised protest", "The drivers voted to go on strike over working conditions.", "take industrial action"],
      ["be made redundant", "essere licenziato per esubero", "to lose a job because the position is no longer needed", "Several employees were made redundant when the office closed.", "lose a position"],
      ["take sick leave", "prendere un congedo per malattia", "to stay away from work because of illness", "She had to take sick leave after the operation.", "be off sick"],
      ["apply for a job", "candidarsi per un lavoro", "to formally ask to be considered for a position", "More than eighty people applied for the job.", "submit an application"],
      ["get promoted", "ottenere una promozione", "to move to a more senior position at work", "He got promoted after successfully leading the project.", "move up"],
      ["plain", "pianura", "a large area of flat land with few trees", "The river crosses a wide plain before reaching the sea.", "flat land"],
      ["ridge", "cresta montuosa", "a long narrow line of high land", "The hikers followed the ridge towards the summit.", "crest"],
      ["tributary", "affluente", "a smaller river or stream that flows into a larger one", "Several tributaries join the main river north of the city.", "branch river"],
      ["estuary", "estuario", "the wide part of a river where it meets the sea", "The estuary provides an important habitat for birds.", "river mouth"],
      ["shallow", "poco profondo", "not having a great distance from the surface to the bottom", "The water is shallow enough to cross safely here.", "not deep"],
      ["widen", "allargare", "to become or make something wider", "The council plans to widen the cycle path.", "make broader"],
      ["shrink", "restringersi o ridursi", "to become smaller in size or amount", "The lake has begun to shrink after months without rain.", "decrease in size"],
      ["breaking news", "notizia dell'ultima ora", "new information about an event that is still developing", "The programme was interrupted by breaking news.", "latest report"],
      ["eyewitness account", "resoconto di un testimone oculare", "a description of an event by someone who saw it", "The article included an eyewitness account of the eruption.", "first-hand report"],
      ["live broadcast", "trasmissione in diretta", "a programme sent out at the same time as the event happens", "Millions watched the live broadcast of the debate.", "real-time transmission"],
      ["news bulletin", "notiziario", "a short radio or television programme that gives recent news", "The warning was repeated in every news bulletin.", "news update"],
      ["surveillance", "sorveglianza", "the careful observation of people or places, often to prevent crime", "The council debated whether more street surveillance was necessary.", "monitoring"],
      ["offence", "reato", "an illegal act or a breach of a rule", "Driving without insurance is a serious offence.", "violation"],
      ["defendant", "imputato", "a person accused of a crime in a court of law", "The defendant denied taking part in the robbery.", "accused person"],
      ["crime rate", "tasso di criminalità", "the amount of crime recorded in a particular place and time", "The crime rate fell after better lighting was installed.", "level of crime"],
      ["high-pitched", "acuto", "having a sound that is high in frequency", "A high-pitched note ended the piece of music.", "shrill"],
    ],
  },
];

export const b2VocabularyItems: VocabularyItem[] = themes.flatMap(
  (theme) =>
    theme.items.map(
      ([term, translation, definition, example, synonym], itemIndex) => ({
        id: `b2v-${String(
          themes
            .slice(0, themes.indexOf(theme))
            .reduce((total, current) => total + current.items.length, 0) +
            itemIndex +
            1,
        ).padStart(3, "0")}`,
        term,
        translation,
        definition,
        example,
        synonym,
        category: theme.category,
        difficulty: "B2" as const,
      }),
    ),
);

function choices<T>(items: T[], index: number, select: (item: T) => string) {
  const candidates = [
    items[index],
    items[(index + 17) % items.length],
    items[(index + 53) % items.length],
    items[(index + 97) % items.length],
  ];
  const unique = [
    ...new Map(candidates.map((item) => [select(item), item])).values(),
  ];
  const offset = index % unique.length;
  return [...unique.slice(offset), ...unique.slice(0, offset)];
}

export const b2VocabularyExercises: Exercise[] = b2VocabularyItems.flatMap(
  (item, index) => {
    const translationChoices = choices(
      b2VocabularyItems,
      index,
      (candidate) => candidate.translation,
    );
    const termChoices = choices(
      b2VocabularyItems,
      index,
      (candidate) => candidate.term,
    );
    const synonymChoices = choices(
      b2VocabularyItems,
      index,
      (candidate) => candidate.synonym,
    );
    const base = {
      section: "vocabulary" as const,
      topic: item.category,
      difficulty: "b2" as const,
      level: "B2" as const,
      explanation: `“${item.term}” significa “${item.translation}”. ${item.definition}.`,
      examples: [{ english: item.example }],
      tags: ["vocabulary", "b2", item.category],
      estimatedTime: 40,
      source: "original" as const,
      createdAt,
    };
    return [
      {
        ...base,
        id: `vocab-${item.id}-translation`,
        type: "multiple-choice" as const,
        question: `Qual è il significato più preciso di “${item.term}”?`,
        instructions: "Scegli la traduzione corretta nel contesto B2.",
        options: translationChoices.map((candidate, optionIndex) => ({
          id: String(optionIndex),
          label: candidate.translation,
        })),
        correctAnswer: item.translation,
      },
      {
        ...base,
        id: `vocab-${item.id}-definition`,
        type: "multiple-choice" as const,
        question: item.definition,
        instructions: "Scegli la parola o espressione inglese descritta.",
        options: termChoices.map((candidate, optionIndex) => ({
          id: String(optionIndex),
          label: candidate.term,
        })),
        correctAnswer: item.term,
      },
      {
        ...base,
        id: `vocab-${item.id}-synonym`,
        type: "synonym" as const,
        question: `Quale opzione è più vicina al significato di “${item.term}”?`,
        instructions: "Scegli il sinonimo o la parafrasi più precisa.",
        options: synonymChoices.map((candidate, optionIndex) => ({
          id: String(optionIndex),
          label: candidate.synonym,
        })),
        correctAnswer: item.synonym,
      },
    ];
  },
);
